package com.bookverse.controller;

import com.bookverse.common.dto.ApiResponse;
import com.bookverse.dto.request.checkout.CheckoutRequestDTO;
import com.bookverse.dto.response.checkout.CheckoutPreviewResponseDTO;
import com.bookverse.dto.response.checkout.CheckoutResponseDTO;
import com.bookverse.service.checkout.CheckoutService;
import com.bookverse.service.payment.PaymentService;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.validation.Valid;
import lombok.RequiredArgsConstructor;
import org.springframework.http.HttpStatus;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.security.core.annotation.AuthenticationPrincipal;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseStatus;
import org.springframework.web.bind.annotation.RestController;

@RestController
@RequestMapping("/api/v1/checkout")
@RequiredArgsConstructor
@Tag(name = "Checkout", description = "Checkout preview and order creation endpoints")
public class CheckoutController {

    private final CheckoutService checkoutService;
    private final PaymentService paymentService;

    @Operation(summary = "Preview checkout totals")
    @io.swagger.v3.oas.annotations.responses.ApiResponse(responseCode = "200", description = "Checkout preview returned")
    @PostMapping("/preview")
    @PreAuthorize("hasRole('CUSTOMER')")
    public ApiResponse<CheckoutPreviewResponseDTO> preview(
            @AuthenticationPrincipal(expression = "user.id") Long userId,
            @Valid @RequestBody CheckoutRequestDTO request) {
        return ApiResponse.success(checkoutService.preview(userId, request));
    }

    @Operation(summary = "Create pending order and payment from current cart")
    @io.swagger.v3.oas.annotations.responses.ApiResponse(responseCode = "201", description = "Checkout created")
    @PostMapping
    @ResponseStatus(HttpStatus.CREATED)
    @PreAuthorize("hasRole('CUSTOMER')")
    public ApiResponse<CheckoutResponseDTO> checkout(
            @AuthenticationPrincipal(expression = "user.id") Long userId,
            @Parameter(description = "Unique idempotency key generated by client", required = true)
            @RequestHeader("Idempotency-Key") String idempotencyKey,
            @Valid @RequestBody CheckoutRequestDTO request,
            HttpServletRequest servletRequest) {
        return ApiResponse.success(
                paymentService.checkout(userId, idempotencyKey, request, clientIp(servletRequest)),
                "Checkout created successfully"
        );
    }

    private String clientIp(HttpServletRequest request) {
        String forwardedFor = request.getHeader("X-Forwarded-For");
        if (forwardedFor != null && !forwardedFor.isBlank()) {
            return forwardedFor.split(",")[0].trim();
        }
        return request.getRemoteAddr();
    }
}
