package com.bookverse.controller;

import com.bookverse.common.dto.ApiResponse;
import com.bookverse.common.dto.PageResponseDTO;
import com.bookverse.dto.request.checkout.CheckoutRequestDTO;
import com.bookverse.dto.request.order.UpdateOrderStatusRequestDTO;
import com.bookverse.dto.response.checkout.CheckoutPreviewResponseDTO;
import com.bookverse.dto.response.checkout.CheckoutResponseDTO;
import com.bookverse.dto.response.order.OrderResponseDTO;
import com.bookverse.dto.response.order.OrderStatusHistoryResponseDTO;
import com.bookverse.dto.response.order.OrderSummaryResponseDTO;
import com.bookverse.dto.response.payment.PendingPaymentLinkResponseDTO;
import com.bookverse.enums.OrderStatus;
import com.bookverse.enums.UserRole;
import com.bookverse.service.checkout.CheckoutService;
import com.bookverse.service.order.OrderService;
import com.bookverse.service.payment.PaymentService;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.validation.Valid;
import lombok.RequiredArgsConstructor;
import org.springframework.data.domain.Pageable;
import org.springframework.http.HttpStatus;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.security.core.annotation.AuthenticationPrincipal;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseStatus;
import org.springframework.web.bind.annotation.RestController;

@RestController
@RequestMapping("/api/v1/orders")
@RequiredArgsConstructor
@Tag(name = "Orders", description = "Order listing, detail and status management API")
public class OrderController {

    private final OrderService orderService;
    private final CheckoutService checkoutService;
    private final PaymentService paymentService;

    @PostMapping("/preview")
    @PreAuthorize("hasRole('CUSTOMER')")
    @Operation(summary = "Preview order totals from selected cart items")
    @io.swagger.v3.oas.annotations.responses.ApiResponse(responseCode = "200", description = "Order preview returned")
    public ApiResponse<CheckoutPreviewResponseDTO> previewOrder(
            @AuthenticationPrincipal(expression = "user.id") Long userId,
            @Valid @RequestBody CheckoutRequestDTO request) {
        return ApiResponse.success(checkoutService.preview(userId, request));
    }

    @PostMapping
    @ResponseStatus(HttpStatus.CREATED)
    @PreAuthorize("hasRole('CUSTOMER')")
    @Operation(summary = "Create pending order and payment from selected cart items")
    @io.swagger.v3.oas.annotations.responses.ApiResponse(responseCode = "201", description = "Order created")
    public ApiResponse<CheckoutResponseDTO> createOrder(
            @AuthenticationPrincipal(expression = "user.id") Long userId,
            @Parameter(description = "Unique idempotency key generated by client", required = true)
            @RequestHeader("Idempotency-Key") String idempotencyKey,
            @Valid @RequestBody CheckoutRequestDTO request,
            HttpServletRequest servletRequest) {
        return ApiResponse.success(
                paymentService.checkout(userId, idempotencyKey, request, clientIp(servletRequest)),
                "Order created successfully"
        );
    }

    @GetMapping
    @PreAuthorize("hasAnyRole('CUSTOMER', 'ADMIN')")
    @Operation(summary = "List current customer orders or admin filtered orders")
    @io.swagger.v3.oas.annotations.responses.ApiResponse(responseCode = "200", description = "Orders returned")
    public ApiResponse<PageResponseDTO<OrderSummaryResponseDTO>> listOrders(
            @AuthenticationPrincipal(expression = "user.id") Long userId,
            @AuthenticationPrincipal(expression = "user.role") UserRole role,
            @RequestParam(required = false) OrderStatus status,
            @RequestParam(required = false) Long customerId,
            Pageable pageable) {
        return ApiResponse.success(orderService.listOrders(userId, role, status, customerId, pageable));
    }

    @GetMapping("/{orderId}")
    @PreAuthorize("hasAnyRole('CUSTOMER', 'ADMIN')")
    @Operation(summary = "Get order detail")
    @io.swagger.v3.oas.annotations.responses.ApiResponse(responseCode = "200", description = "Order returned")
    public ApiResponse<OrderResponseDTO> getOrder(
            @AuthenticationPrincipal(expression = "user.id") Long userId,
            @AuthenticationPrincipal(expression = "user.role") UserRole role,
            @PathVariable Long orderId) {
        return ApiResponse.success(orderService.getOrder(userId, role, orderId));
    }

    @PostMapping("/{orderId}/cancel")
    @PreAuthorize("hasRole('CUSTOMER')")
    @Operation(summary = "Cancel current customer pending payment order")
    @io.swagger.v3.oas.annotations.responses.ApiResponse(responseCode = "200", description = "Order cancelled")
    public ApiResponse<OrderResponseDTO> cancelOrder(
            @AuthenticationPrincipal(expression = "user.id") Long userId,
            @PathVariable Long orderId) {
        return ApiResponse.success(orderService.cancelPendingOrder(userId, orderId), "Order cancelled successfully");
    }

    @GetMapping("/{orderId}/payment-link")
    @PreAuthorize("hasRole('CUSTOMER')")
    @Operation(summary = "Get the active VNPAY link for a pending order")
    @io.swagger.v3.oas.annotations.responses.ApiResponse(responseCode = "200", description = "Payment link returned")
    public ApiResponse<PendingPaymentLinkResponseDTO> getPendingPaymentLink(
            @AuthenticationPrincipal(expression = "user.id") Long userId,
            @PathVariable Long orderId) {
        return ApiResponse.success(paymentService.getPendingPaymentLink(userId, orderId));
    }

    @GetMapping("/{orderId}/status-history")
    @PreAuthorize("hasAnyRole('CUSTOMER', 'ADMIN')")
    @Operation(summary = "Get order status history")
    @io.swagger.v3.oas.annotations.responses.ApiResponse(responseCode = "200", description = "Order status history returned")
    public ApiResponse<PageResponseDTO<OrderStatusHistoryResponseDTO>> getStatusHistory(
            @AuthenticationPrincipal(expression = "user.id") Long userId,
            @AuthenticationPrincipal(expression = "user.role") UserRole role,
            @PathVariable Long orderId,
            Pageable pageable) {
        return ApiResponse.success(orderService.getStatusHistory(userId, role, orderId, pageable));
    }

    @PutMapping("/{orderId}/status")
    @PreAuthorize("hasRole('ADMIN')")
    @Operation(summary = "Admin transition order status")
    @io.swagger.v3.oas.annotations.responses.ApiResponse(responseCode = "200", description = "Order status updated")
    public ApiResponse<OrderResponseDTO> updateStatus(
            @AuthenticationPrincipal(expression = "user.id") Long adminUserId,
            @PathVariable Long orderId,
            @Valid @RequestBody UpdateOrderStatusRequestDTO request) {
        return ApiResponse.success(orderService.updateStatus(adminUserId, orderId, request), "Order status updated successfully");
    }

    private String clientIp(HttpServletRequest request) {
        String forwardedFor = request.getHeader("X-Forwarded-For");
        if (forwardedFor != null && !forwardedFor.isBlank()) {
            return forwardedFor.split(",")[0].trim();
        }
        return request.getRemoteAddr();
    }
}
