
INSERT INTO categories (name, slug, active, created_at, updated_at) VALUES ('Business & Finance', 'business-finance', true, now(), now()) ON CONFLICT (name) DO NOTHING;


INSERT INTO categories (name, slug, active, created_at, updated_at) VALUES ('Technology & Computing', 'technology-computing', true, now(), now()) ON CONFLICT (name) DO NOTHING;


INSERT INTO categories (name, slug, active, created_at, updated_at) VALUES ('Psychology & Self-Help', 'psychology-self-help', true, now(), now()) ON CONFLICT (name) DO NOTHING;


INSERT INTO categories (name, slug, active, created_at, updated_at) VALUES ('Science & Mathematics', 'science-mathematics', true, now(), now()) ON CONFLICT (name) DO NOTHING;


INSERT INTO categories (name, slug, active, created_at, updated_at) VALUES ('Education', 'education', true, now(), now()) ON CONFLICT (name) DO NOTHING;


INSERT INTO categories (name, slug, active, created_at, updated_at) VALUES ('Children''s Books', 'childrens-books', true, now(), now()) ON CONFLICT (name) DO NOTHING;


INSERT INTO categories (name, slug, active, created_at, updated_at) VALUES ('History, Politics & International Relations', 'history-politics-international-relations', true, now(), now()) ON CONFLICT (name) DO NOTHING;


INSERT INTO categories (name, slug, active, created_at, updated_at) VALUES ('Fiction & Literature', 'fiction-literature', true, now(), now()) ON CONFLICT (name) DO NOTHING;


INSERT INTO categories (name, slug, active, created_at, updated_at) VALUES ('Social Sciences', 'social-sciences', true, now(), now()) ON CONFLICT (name) DO NOTHING;


INSERT INTO categories (name, slug, active, created_at, updated_at) VALUES ('Health & Fitness', 'health-fitness', true, now(), now()) ON CONFLICT (name) DO NOTHING;


INSERT INTO categories (name, slug, active, created_at, updated_at) VALUES ('Religion & Spirituality', 'religion-spirituality', true, now(), now()) ON CONFLICT (name) DO NOTHING;



INSERT INTO books (title, author, isbn, publisher, publication_year, language, pages, category_id, price, original_price, stock, description, rating_avg, review_count, sold_count, active, created_at, updated_at, cover_key, file_key) 
VALUES ('101 Creative Problem Solving Techniques: The Handbook of New Ideas for Business', 'James M. Higgins', '9781883629007', 'New Management Publishing Company, Inc.', 1994, 'en', 223, (SELECT id FROM categories WHERE name = 'Business & Finance'), 75000, 97500, 100, 'Cuốn sách 101 Creative Problem Solving Techniques đề cập đến chủ đề giải quyết vấn đề một cách sáng tạo và đổi mới trong môi trường kinh doanh đầy biến động. Nội dung chính của cuốn sách là sự trình bày chi tiết về quy trình giải quyết vấn đề sáng tạo (Creative Problem Solving - CPS) cùng với 101 kỹ thuật cụ thể nhằm kích thích khả năng sáng tạo của cá nhân và nhóm. Các kỹ thuật này bao gồm nhiều phương pháp nổi bật như động não (brainstorming), lập bản đồ tư duy (mind mapping), sử dụng công nghệ hỗ trợ, và nhiều phương pháp phân tích, tạo ra các giải pháp thay thế. Đối tượng phù hợp nhất cho cuốn sách là các nhà quản lý, trưởng nhóm, các chuyên gia và bất kỳ nhân viên nào muốn nâng cao hiệu suất làm việc của bản thân hoặc đội ngũ thông qua tư duy sáng tạo. Giá trị của cuốn sách nằm ở chỗ nó cung cấp một bộ công cụ thực tế, dễ áp dụng, giúp các cá nhân và tổ chức không chỉ nhận diện đúng vấn đề mà còn tạo ra được những ý tưởng đột phá, từ đó nâng cao năng lực cạnh tranh và sự đổi mới liên tục trong doanh nghiệp.', 0, 0, 0, true, now(), now(), '101_Creative_Problem_Solvin.png', '101_Creative_Problem_Solvin.pdf') ON CONFLICT (isbn) WHERE isbn IS NOT NULL DO NOTHING;


INSERT INTO books (title, author, isbn, publisher, publication_year, language, pages, category_id, price, original_price, stock, description, rating_avg, review_count, sold_count, active, created_at, updated_at, cover_key, file_key) 
VALUES ('AI Engineering: Building Applications with Foundation Models', 'Chip Huyen', '9781098166304', 'O''Reilly Media, Inc.', 2024, 'en', NULL, (SELECT id FROM categories WHERE name = 'Technology & Computing'), 90000, 117000, 100, 'Cuốn sách AI Engineering: Building Applications with Foundation Models tập trung vào chủ đề kỹ thuật trí tuệ nhân tạo (AI Engineering), cụ thể là quy trình xây dựng các ứng dụng dựa trên các mô hình nền tảng (Foundation Models) như LLMs và LMMs. Nội dung chính bao quát toàn bộ vòng đời phát triển ứng dụng AI, từ việc hiểu rõ cách thức hoạt động của các mô hình, cách đánh giá và lựa chọn mô hình, cho đến việc áp dụng các kỹ thuật như Prompt Engineering, Retrieval-Augmented Generation (RAG), xây dựng các AI Agents và tinh chỉnh mô hình (Finetuning). Sách cũng đi sâu vào việc tối ưu hóa suy luận (inference optimization) để giảm độ trễ và chi phí. Đối tượng phù hợp của cuốn sách là các kỹ sư AI, kỹ sư học máy (ML engineers), nhà khoa học dữ liệu, các nhà quản lý kỹ thuật và những người phát triển phần mềm muốn tích hợp AI vào sản phẩm. Giá trị của cuốn sách là mang lại một khung làm việc có hệ thống, những kiến thức nền tảng vượt thời gian về thiết kế hệ thống AI, giúp người đọc thu hẹp khoảng cách giữa việc tạo ra các bản thử nghiệm và triển khai ứng dụng mạnh mẽ trong thực tế.', 0, 0, 0, true, now(), now(), 'AI_Engineering_Building_App.png', 'AI_Engineering_Building_App.pdf') ON CONFLICT (isbn) WHERE isbn IS NOT NULL DO NOTHING;


INSERT INTO books (title, author, isbn, publisher, publication_year, language, pages, category_id, price, original_price, stock, description, rating_avg, review_count, sold_count, active, created_at, updated_at, cover_key, file_key) 
VALUES ('A Trader''s Money Management System: How to Ensure Profit and Avoid the Risk of Ruin', 'Bennett A. McDowell', '9780470187715', 'John Wiley & Sons, Inc.', 2008, 'en', NULL, (SELECT id FROM categories WHERE name = 'Business & Finance'), 105000, 136500, 100, 'Cuốn sách A Trader''s Money Management System: How to Ensure Profit and Avoid the Risk of Ruin tập trung vào chủ đề quản lý vốn và quản trị rủi ro trong lĩnh vực giao dịch tài chính và đầu tư. Nội dung chính của tài liệu nhấn mạnh vào việc thiết lập một hệ thống quản lý tiền bạc thiết thực và các quy tắc kiểm soát rủi ro, nhằm giúp người tham gia thị trường tránh được nguy cơ phá sản, đồng thời bảo vệ tài khoản và tối ưu hóa lợi nhuận trong quá trình giao dịch. Sách cũng đề cập đến các công thức toán học làm nền tảng cho các kỹ thuật quản lý rủi ro này. Đối tượng phù hợp của cuốn sách là các nhà giao dịch (trader), nhà đầu tư chứng khoán, chuyên gia tài chính và những cá nhân mong muốn xây dựng một chiến lược đầu tư bài bản và an toàn. Giá trị lớn nhất của cuốn sách là thúc đẩy người đọc hành động ngay lập tức để trang bị hệ thống quản lý rủi ro, cung cấp phương pháp có khả năng áp dụng vào thực tiễn một cách hiệu quả, giúp nâng tầm kỹ năng giao dịch và đảm bảo sự phát triển bền vững trên thị trường tài chính đầy khốc liệt.', 0, 0, 0, true, now(), now(), 'A_Traders_Money_Management.png', 'A_Traders_Money_Management.pdf') ON CONFLICT (isbn) WHERE isbn IS NOT NULL DO NOTHING;


INSERT INTO books (title, author, isbn, publisher, publication_year, language, pages, category_id, price, original_price, stock, description, rating_avg, review_count, sold_count, active, created_at, updated_at, cover_key, file_key) 
VALUES ('Adult Children of Emotionally Immature Parents: How to Heal from Distant, Rejecting, or Self-Involved Parents', 'Lindsay C. Gibson', '9781626251700', 'New Harbinger Publications, Inc.', 2015, 'en', NULL, (SELECT id FROM categories WHERE name = 'Psychology & Self-Help'), 120000, 156000, 100, 'Cuốn sách Adult Children of Emotionally Immature Parents tập trung vào chủ đề tâm lý học gia đình và hành trình chữa lành cho những cá nhân lớn lên cùng những người cha, người mẹ thiếu trưởng thành về mặt cảm xúc. Nội dung chính của tác phẩm đi sâu phân tích cách mà những phụ huynh xa cách, hay từ chối hoặc chỉ biết đến bản thân gây ra những tổn thương tâm lý sâu sắc cho con cái họ. Tác giả phân loại bốn kiểu cha mẹ thiếu trưởng thành về cảm xúc và giải thích cách những đứa trẻ phản ứng lại thông qua việc nội tâm hóa (internalizer) hoặc ngoại hiện hóa (externalizer). Đối tượng phù hợp nhất của cuốn sách là những người trưởng thành từng trải qua tuổi thơ thiếu vắng sự kết nối tình cảm, đặc biệt là nhóm người hướng nội đang tìm kiếm sự thấu hiểu về bản thân và những người xung quanh. Giá trị của cuốn sách nằm ở việc nó cung cấp một cái nhìn khách quan, khoa học để giải mã các động lực tâm lý gia đình độc hại, đồng thời mang đến các phương pháp thực tiễn giúp người đọc tránh bị thao túng, giải phóng bản thân khỏi những vai trò và ảo tưởng xưa cũ để xây dựng các mối quan hệ lành mạnh, trưởng thành hơn.', 0, 0, 0, true, now(), now(), 'Adult_Children_of_Emotional.png', 'Adult_Children_of_Emotional.pdf') ON CONFLICT (isbn) WHERE isbn IS NOT NULL DO NOTHING;


INSERT INTO books (title, author, isbn, publisher, publication_year, language, pages, category_id, price, original_price, stock, description, rating_avg, review_count, sold_count, active, created_at, updated_at, cover_key, file_key) 
VALUES ('Cây cỏ Việt Nam (An Illustrated Flora of Vietnam) - Quyển I', 'Phạm Hoàng Hộ', NULL, 'Nhà Xuất Bản Trẻ', 1999, 'vi', NULL, (SELECT id FROM categories WHERE name = 'Science & Mathematics'), 135000, 175500, 100, 'Cuốn sách Cây cỏ Việt Nam (An Illustrated Flora of Vietnam) - Quyển I là một công trình khoa học đồ sộ mang tầm cỡ quốc gia, đi sâu vào chủ đề phân loại học và mô tả chi tiết hệ sinh thái thực vật phong phú của Việt Nam. Nội dung chính của Quyển I tập trung phân loại, điểm danh và minh họa bằng hình ảnh đối với hàng ngàn giống loài thực vật, trải dài từ nhóm Khuyết thực vật, Lõa tử, Hoa cánh rời cho đến các cây thuộc họ Đậu. Tác giả đã trình bày các loài theo những tiêu chí khoa học nghiêm ngặt với độ chính xác cao. Đối tượng phù hợp để đọc và sử dụng sách là các nhà nghiên cứu sinh học, thực vật học, sinh viên các ngành khoa học tự nhiên, cũng như những người yêu thiên nhiên và mong muốn tìm hiểu về hệ thực vật nước nhà. Giá trị cốt lõi của cuốn sách không chỉ nằm ở khối lượng kiến thức khổng lồ được tích lũy bằng tâm huyết cả đời của giáo sư Phạm Hoàng Hộ, mà còn là một lời kêu gọi cấp thiết về ý thức bảo tồn thiên nhiên, bảo vệ rừng và nguồn tài nguyên thực vật quý giá của Việt Nam trước nguy cơ bị tuyệt chủng và xói mòn.', 0, 0, 0, true, now(), now(), NULL, NULL) ;


INSERT INTO books (title, author, isbn, publisher, publication_year, language, pages, category_id, price, original_price, stock, description, rating_avg, review_count, sold_count, active, created_at, updated_at, cover_key, file_key) 
VALUES ('Attacking the Elites: What Critics Get Wrong-and Right-About America''s Leading Universities', 'Derek Bok', '9780300273601', 'Yale University Press', 2024, 'en', NULL, (SELECT id FROM categories WHERE name = 'Education'), 150000, 195000, 100, 'Cuốn sách Attacking the Elites: What Critics Get Wrong-and Right-About America''s Leading Universities tập trung vào chủ đề giáo dục đại học tại Mỹ, cụ thể là việc phân tích các luồng ý kiến chỉ trích nhắm vào các trường đại học tinh hoa. Nội dung chính của tác phẩm đi sâu khám phá vai trò và trách nhiệm của các cơ sở giáo dục hàng đầu này đối với xã hội Mỹ. Tác giả thảo luận chi tiết về các vấn đề nhức nhối như chính sách tuyển sinh trong bối cảnh bất bình đẳng cực đoan, trách nhiệm dân sự, các cuộc biểu tình của sinh viên chống lại sự bất công, cũng như những giới hạn và rào cản của tự do ngôn luận trong khuôn viên trường học. Cuốn sách đặc biệt phù hợp với những độc giả quan tâm đến hệ thống giáo dục đại học, các nhà hoạch định chính sách, các nhà nghiên cứu xã hội học và chính những sinh viên, giảng viên đang làm việc tại các trường đại học. Giá trị của cuốn sách nằm ở chỗ nó cung cấp một góc nhìn khách quan và đa chiều, phân định rõ ràng những điểm đúng và sai trong những lời chỉ trích từ công chúng, qua đó thúc đẩy tư duy phản biện về cách mà các trường đại học tinh hoa có thể đóng góp hiệu quả hơn cho xã hội và nền dân chủ.', 0, 0, 0, true, now(), now(), 'Attacking_the_Elites.png', 'Attacking_the_Elites.pdf') ON CONFLICT (isbn) WHERE isbn IS NOT NULL DO NOTHING;


INSERT INTO books (title, author, isbn, publisher, publication_year, language, pages, category_id, price, original_price, stock, description, rating_avg, review_count, sold_count, active, created_at, updated_at, cover_key, file_key) 
VALUES ('Bạn Không Thông Minh Lắm Đâu', 'David McRaney', NULL, 'Nhà Xuất Bản Thế Giới', NULL, 'vi', NULL, (SELECT id FROM categories WHERE name = 'Psychology & Self-Help'), 165000, 214500, 100, 'Cuốn sách Bạn Không Thông Minh Lắm Đâu mang đến một cái nhìn sâu sắc và thú vị về chủ đề tâm lý học nhận thức, tập trung giải mã những cách thức mà bộ não con người tự đánh lừa chính mình. Nội dung chính của sách là bản tóm tắt chi tiết về hàng loạt các hiện tượng tâm lý quen thuộc bao gồm thiên kiến nhận thức (cognitive biases), sự tự nghiệm (heuristics) và những phương pháp ngụy biện logic (logical fallacies). Thông qua các ví dụ thực tế và các thí nghiệm khoa học, tác giả lần lượt bóc trần những ảo tưởng của chúng ta như thiên kiến xác nhận, hiệu ứng Dunning-Kruger, sự trì hoãn hay hiệu ứng mỏ neo. Đối tượng phù hợp của tác phẩm là những độc giả đại chúng tò mò về tâm lý học hành vi, cũng như bất kỳ ai muốn thấu hiểu cơ chế hoạt động ẩn sâu bên trong trí não mình. Giá trị cốt lõi của cuốn sách là sự thức tỉnh, giúp người đọc nhận ra rằng bản thân không hề khách quan và lý trí như họ vẫn lầm tưởng. Bằng việc bóc tách những rào cản tâm lý này, cuốn sách cung cấp một liều thuốc hoài nghi cần thiết, giúp chúng ta khiêm tốn hơn và đưa ra những quyết định sáng suốt hơn trong cuộc sống hàng ngày.', 0, 0, 0, true, now(), now(), 'Ban_Khong_Thong_Minh_Lam_Da.png', 'Ban_Khong_Thong_Minh_Lam_Da.pdf') ;


INSERT INTO books (title, author, isbn, publisher, publication_year, language, pages, category_id, price, original_price, stock, description, rating_avg, review_count, sold_count, active, created_at, updated_at, cover_key, file_key) 
VALUES ('Bí mật thế giới động vật: Vương quốc khủng long', 'Nhiều tác giả', '9786046431541', 'Nhà Xuất Bản Thanh Niên', 2016, 'vi', NULL, (SELECT id FROM categories WHERE name = 'Children''s Books'), 180000, 234000, 100, 'Cuốn sách Bí mật thế giới động vật: Vương quốc khủng long là một ấn phẩm khoa học thiếu nhi hấp dẫn, tập trung vào chủ đề khám phá thế giới của loài khủng long thời tiền sử. Nội dung chính của sách dẫn dắt người đọc bước vào một cuộc hành trình xuyên thời gian qua ba kỷ nguyên địa chất: kỷ Tam Điệp, kỷ Jura và kỷ Phấn Trắng. Sách cung cấp kiến thức chi tiết về nguồn gốc, cách phân loại (khủng long hông chim và hông thằn lằn), tập tính sinh hoạt, kiếm mồi, sinh sản, cũng như các giả thuyết về sự tuyệt chủng thần bí của gia tộc khổng lồ này. Bên cạnh đó, tác phẩm còn mô tả quá trình hình thành và khai quật hóa thạch, vốn là chìa khóa để con người tìm hiểu về khủng long. Đối tượng phù hợp nhất của cuốn sách là các em thiếu nhi, học sinh và những độc giả nhỏ tuổi có niềm đam mê với khoa học tự nhiên và động vật học. Giá trị của cuốn sách nằm ở sự kết hợp hài hòa giữa ngôn ngữ kể chuyện đơn giản, dễ hiểu cùng với hệ thống hình ảnh minh họa vô cùng sinh động, giúp khơi dậy trí tò mò, mở rộng vốn hiểu biết và nuôi dưỡng tình yêu khám phá khoa học ở trẻ nhỏ.', 0, 0, 0, true, now(), now(), 'Bi_Mat_The_Gioi_Dong_Vat.png', 'Bi_Mat_The_Gioi_Dong_Vat.pdf') ON CONFLICT (isbn) WHERE isbn IS NOT NULL DO NOTHING;


INSERT INTO books (title, author, isbn, publisher, publication_year, language, pages, category_id, price, original_price, stock, description, rating_avg, review_count, sold_count, active, created_at, updated_at, cover_key, file_key) 
VALUES ('Biophysical Chemistry', 'Alan Cooper', '9780854044801', 'Royal Society of Chemistry', 2004, 'en', 184, (SELECT id FROM categories WHERE name = 'Science & Mathematics'), 195000, 253500, 100, 'Cuốn sách Biophysical Chemistry là một tài liệu học tập chuyên sâu xoay quanh chủ đề hóa lý của các đại phân tử sinh học. Nội dung chính của cuốn sách bao quát sự kết hợp giữa các nguyên lý vật lý và hệ thống sinh học, cung cấp kiến thức toàn diện về cấu trúc, động lực học và các tương tác của protein, axit nucleic, lipid và carbohydrate trong môi trường nước. Tác giả trình bày chi tiết về các phương pháp thực nghiệm quan trọng như quang phổ học (UV/Visible, huỳnh quang, NMR, tán sắc Raman), khối phổ, các nguyên lý thủy động lực học, nhiệt động lực học phân tử và động học của các phản ứng enzyme. Đối tượng phù hợp của cuốn sách là các sinh viên đại học trong những năm đầu thuộc chuyên ngành hóa học, vật lý, sinh học hoặc hóa sinh, cũng như những nhà khoa học cần một tài liệu cơ sở vững chắc về lý thuyết và thực nghiệm hóa lý. Giá trị nổi bật của tác phẩm nằm ở cách tiếp cận thiên về thực nghiệm, giúp người học không chỉ nắm bắt được lý thuyết mà còn hiểu rõ cách thức sử dụng các công cụ vật lý để giải mã các cơ chế vận hành phức tạp của các phân tử sự sống, từ đó mở ra tiềm năng ứng dụng to lớn trong y sinh và khoa học môi trường.', 0, 0, 0, true, now(), now(), 'Biophysical_chemistry.png', 'Biophysical_chemistry.pdf') ON CONFLICT (isbn) WHERE isbn IS NOT NULL DO NOTHING;


INSERT INTO books (title, author, isbn, publisher, publication_year, language, pages, category_id, price, original_price, stock, description, rating_avg, review_count, sold_count, active, created_at, updated_at, cover_key, file_key) 
VALUES ('Boundaries and Relationships: Knowing, Protecting and Enjoying the Self', 'Charles L. Whitfield', '9781558742598', 'Health Communications, Inc.', 1993, 'en', NULL, (SELECT id FROM categories WHERE name = 'Psychology & Self-Help'), 210000, 273000, 100, 'Cuốn sách "Boundaries and Relationships: Knowing, Protecting and Enjoying the Self" tập trung vào chủ đề tâm lý học, cụ thể là việc thiết lập ranh giới cá nhân và phát triển các mối quan hệ lành mạnh. Về nội dung chính, tác phẩm cung cấp một cái nhìn sâu sắc về cách định hình và duy trì các ranh giới bảo vệ không gian thể chất, tinh thần, cảm xúc và tâm linh của mỗi người. Thông qua việc phân tích các khái niệm cốt lõi như "Đứa trẻ bên trong" (True Self), cái tôi giả tạo (false self), hiện tượng thoái lùi tuổi tác (age regression), và sự phụ thuộc lẫn nhau (co-dependence), tác giả hướng dẫn cách phân biệt đâu là giới hạn an toàn để không bị lạm dụng hoặc đánh mất chính mình. Đối tượng phù hợp của cuốn sách bao gồm cả những độc giả phổ thông đang tìm kiếm sự bình yên, muốn cải thiện chất lượng các mối quan hệ, cũng như các chuyên gia tâm lý và chuyên viên tư vấn hỗ trợ quá trình phục hồi tâm lý. Giá trị của cuốn sách nằm ở việc cung cấp một lộ trình rõ ràng giúp người đọc thấu hiểu nội tâm, bảo vệ sự toàn vẹn của tâm hồn, tránh được những đau khổ không đáng có trong các mối quan hệ và đạt được sự thanh thản trong cuộc sống.', 0, 0, 0, true, now(), now(), 'Boundaries_and_relationship.png', 'Boundaries_and_relationship.pdf') ON CONFLICT (isbn) WHERE isbn IS NOT NULL DO NOTHING;


INSERT INTO books (title, author, isbn, publisher, publication_year, language, pages, category_id, price, original_price, stock, description, rating_avg, review_count, sold_count, active, created_at, updated_at, cover_key, file_key) 
VALUES ('Brain Training: the complete visual program', 'James Harrison, Mike Hobbs', '9780756657307', 'DK Publishing', 2010, 'en', NULL, (SELECT id FROM categories WHERE name = 'Psychology & Self-Help'), 225000, 292500, 100, '"Brain Training: the complete visual program" xoay quanh chủ đề rèn luyện trí não, phát triển nhận thức và tăng cường năng lực tư duy trực quan của con người. Nội dung chính của cuốn sách là một chương trình huấn luyện toàn diện dựa trên nền tảng học tập trực quan. Nó lý giải cấu trúc và tiềm năng của não bộ, khái niệm về trí thông minh và khẳng định rằng bộ não có thể được rèn luyện để phát triển giống như cơ bắp. Tác giả cung cấp hàng loạt bài tập, câu đố và kỹ thuật thực hành trải dài trên nhiều lĩnh vực: cải thiện trí nhớ (sử dụng Phương pháp Hành trình - Journey Method, hay chốt trí nhớ - Pegging), nhận thức không gian, tư duy hình ảnh, lý luận toán học, suy luận ngôn ngữ và tư duy sáng tạo. Bên cạnh đó, sách cũng nhấn mạnh mối liên hệ mật thiết giữa thể chất và tinh thần để tối ưu sức mạnh não bộ. Đối tượng phù hợp của cuốn sách là mọi cá nhân ở các độ tuổi muốn nâng cao năng lực trí tuệ, cải thiện khả năng tập trung, cũng như những người muốn ngăn ngừa sự suy giảm nhận thức. Giá trị của cuốn sách là mang lại các công cụ thực tiễn giúp người đọc tối đa hóa nguồn vốn trí tuệ, khơi dậy tiềm năng thiên tài và duy trì sự nhạy bén của tinh thần.', 0, 0, 0, true, now(), now(), 'Brain_Training_Boost_Memory.png', 'Brain_Training_Boost_Memory.pdf') ON CONFLICT (isbn) WHERE isbn IS NOT NULL DO NOTHING;


INSERT INTO books (title, author, isbn, publisher, publication_year, language, pages, category_id, price, original_price, stock, description, rating_avg, review_count, sold_count, active, created_at, updated_at, cover_key, file_key) 
VALUES ('Building Event-Driven Microservices: Leveraging Organizational Data at Scale', 'Adam Bellemare', '9781492057895', 'O''Reilly Media, Inc.', 2020, 'en', NULL, (SELECT id FROM categories WHERE name = 'Technology & Computing'), 240000, 312000, 100, 'Tác phẩm "Building Event-Driven Microservices: Leveraging Organizational Data at Scale" tập trung vào chủ đề kiến trúc phần mềm, cụ thể là việc phát triển các hệ thống microservices theo hướng sự kiện nhằm khai thác dữ liệu ở quy mô lớn. Nội dung chính của cuốn sách trình bày chi tiết cách thiết kế và triển khai kiến trúc dựa trên sự kiện (event-driven). Tác giả Adam Bellemare giải thích các nguyên tắc như thiết kế hướng tên miền (Domain-Driven Design), khái niệm Bounded Contexts, và cách thức dữ liệu được giải phóng (data liberation) từ các hệ thống cũ để trở thành nguồn dữ liệu chân lý duy nhất thông qua event broker (như Apache Kafka). Cuốn sách cung cấp các mẫu kiến trúc đa dạng, phương pháp xử lý luồng dữ liệu, cũng như cách tích hợp microservices hướng sự kiện với các hệ thống request-response và Function-as-a-Service (FaaS). Đối tượng phù hợp của tác phẩm là các kiến trúc sư phần mềm, kỹ sư dữ liệu và lập trình viên đang đối mặt với bài toán mở rộng hệ thống, cũng như các tổ chức cần xử lý lượng dữ liệu khổng lồ theo thời gian thực. Giá trị cốt lõi của cuốn sách là cung cấp các giải pháp thiết kế thực tiễn nhằm giảm bớt sự phức tạp trong giao tiếp hệ thống, giúp doanh nghiệp linh hoạt hơn và mở khóa quyền truy cập dữ liệu một cách hiệu quả nhất.', 0, 0, 0, true, now(), now(), 'Building_Event-Driven_Micro.png', 'Building_Event-Driven_Micro.pdf') ON CONFLICT (isbn) WHERE isbn IS NOT NULL DO NOTHING;


INSERT INTO books (title, author, isbn, publisher, publication_year, language, pages, category_id, price, original_price, stock, description, rating_avg, review_count, sold_count, active, created_at, updated_at, cover_key, file_key) 
VALUES ('Building Microservices: Designing Fine-Grained Systems', 'Sam Newman', '9781492034025', 'O''Reilly Media, Inc.', 2021, 'en', NULL, (SELECT id FROM categories WHERE name = 'Technology & Computing'), 255000, 331500, 100, 'Chủ đề của cuốn sách "Building Microservices: Designing Fine-Grained Systems" là thiết kế, xây dựng và quản lý kiến trúc phần mềm microservices chi tiết, giúp các hệ thống hoạt động độc lập và hiệu quả. Nội dung chính của tác phẩm là hướng dẫn toàn diện quá trình chuyển đổi từ các hệ thống nguyên khối khổng lồ (monoliths) sang kiến trúc microservices linh hoạt. Tác giả phân tích toàn bộ vòng đời của hệ thống: từ việc xác định ranh giới dịch vụ thông qua thiết kế hướng tên miền (Domain-Driven Design), cách chia tách cơ sở dữ liệu, quản lý quy trình tích hợp và triển khai liên tục (CI/CD, sử dụng container như Kubernetes), cho đến việc kiểm thử, giám sát (observability), bảo mật và khả năng phục hồi (resiliency) của dịch vụ. Sách còn đề cập đến Định luật Conway để điều chỉnh cấu trúc tổ chức cho phù hợp với kiến trúc công nghệ. Đối tượng phù hợp là các kiến trúc sư phần mềm, lập trình viên, kỹ sư kiểm thử (testers) và các chuyên gia vận hành hệ thống IT (operators) đang mong muốn tối ưu hóa kiến trúc ứng dụng. Giá trị lớn nhất của cuốn sách là mang lại một cẩm nang định hướng thực tiễn, giúp độc giả hiểu rõ ưu nhược điểm của microservices để đưa ra các quyết định thiết kế đúng đắn và xây dựng hệ thống bền vững.', 0, 0, 0, true, now(), now(), 'Building_Microservices_Desi.png', 'Building_Microservices_Desi.pdf') ON CONFLICT (isbn) WHERE isbn IS NOT NULL DO NOTHING;


INSERT INTO books (title, author, isbn, publisher, publication_year, language, pages, category_id, price, original_price, stock, description, rating_avg, review_count, sold_count, active, created_at, updated_at, cover_key, file_key) 
VALUES ('Các cổng của Văn Miếu - Quốc Tử Giám', 'Trung tâm hoạt động Văn hóa Khoa học Văn Miếu - Quốc Tử Giám', '9786048093143', 'Nhà xuất bản Thông tin và Truyền thông', 2024, 'vi', NULL, (SELECT id FROM categories WHERE name = 'History, Politics & International Relations'), 270000, 351000, 100, 'Tác phẩm "Các cổng của Văn Miếu - Quốc Tử Giám" đi sâu vào chủ đề lịch sử, kiến trúc và ý nghĩa văn hóa của hệ thống các cổng trong khu di tích giáo dục lâu đời nhất Việt Nam. Về nội dung chính, tài liệu tập trung mô tả chi tiết đặc điểm kết cấu, vị trí địa lý và ý nghĩa biểu tượng của các lớp cổng nằm trong quần thể Văn Miếu - Quốc Tử Giám. Dọc theo trục Bắc - Nam, sách giới thiệu 5 cổng chính bao gồm: Cổng Văn Miếu, cổng Đại Trung, Khuê Văn Các, cổng Đại Thành và cổng Thái Học, cùng với các cổng phụ mang ý nghĩa đặc biệt như Thành Đức, Đạt Tài, Bí Văn, Súc Văn, Kim Thanh và Ngọc Chấn. Bằng việc phân tích các hoa văn trang trí tinh xảo, các mảng chạm khắc rồng, cá chép, ngũ lão, và triết lý phong thủy âm dương, nội dung làm nổi bật tinh thần tôn sư trọng đạo và khát vọng bồi dưỡng hiền tài của người xưa. Đối tượng phù hợp của cuốn sách là những người yêu thích lịch sử, văn hóa, kiến trúc cổ Việt Nam, học sinh, sinh viên, nhà nghiên cứu cũng như khách du lịch. Giá trị của sách nằm ở việc bảo tồn và truyền tải ý nghĩa triết học sâu sắc của nền giáo dục Nho học, khẳng định vẻ đẹp văn hóa tri thức của dân tộc.', 0, 0, 0, true, now(), now(), 'Cac_cong_cua_Van_Mieu_-_Quo.png', 'Cac_cong_cua_Van_Mieu_-_Quo.pdf') ON CONFLICT (isbn) WHERE isbn IS NOT NULL DO NOTHING;


INSERT INTO books (title, author, isbn, publisher, publication_year, language, pages, category_id, price, original_price, stock, description, rating_avg, review_count, sold_count, active, created_at, updated_at, cover_key, file_key) 
VALUES ('Cây Cam Ngọt Của Tôi', 'José Mauro de Vasconcelos', NULL, 'Nhà Xuất Bản Hội Nhà Văn', 2021, 'vi', NULL, (SELECT id FROM categories WHERE name = 'Fiction & Literature'), 285000, 370500, 100, 'Cuốn tiểu thuyết "Cây Cam Ngọt Của Tôi" mang chủ đề về tâm lý tuổi thơ, sự thấu hiểu nỗi đau và hành trình khám phá tình yêu thương trong cuộc sống khốn khó. Nội dung chính của câu chuyện xoay quanh cuộc sống nội tâm cực kỳ phong phú nhưng đầy bi kịch của Zezé, một cậu bé mới năm tuổi sinh ra trong một gia đình nghèo khó. Vì bản tính tinh nghịch và trí tưởng tượng khác thường, Zezé thường xuyên phải hứng chịu những trận đòn roi tàn nhẫn và sự ghẻ lạnh từ người thân. Chỗ dựa tinh thần duy nhất của cậu bé là một cây cam ngọt nhỏ nhắn ở sân sau mà cậu gọi là Pinkie, nơi cậu trút bầu tâm sự và chìm đắm trong thế giới mộng mơ. Cuộc sống của cậu có thêm tia sáng khi kết bạn với ông Manuel Valadares (ông Bồ), người đã mang đến cho Zezé tình yêu thương chân thành và sự che chở ấm áp. Tuy nhiên, những biến cố đau lòng liên tiếp ập đến đã buộc cậu bé phải từ giã sự ngây thơ tuổi nhỏ. Đối tượng phù hợp của tác phẩm là mọi độc giả từ lứa tuổi thiếu niên đến người trưởng thành, những ai muốn tìm lại sự rung cảm sâu sắc và cái nhìn thấu cảm về thế giới của trẻ em. Giá trị của cuốn tiểu thuyết nằm ở thông điệp nhân văn to lớn về sức mạnh chữa lành của sự dịu dàng và lời nhắc nhở sâu sắc về cách người lớn thấu hiểu, bảo vệ những tâm hồn nhạy cảm của trẻ thơ.', 0, 0, 0, true, now(), now(), 'Cay_Cam_Ngot_Cua_Toi_etc.png', 'Cay_Cam_Ngot_Cua_Toi_etc.pdf') ;


INSERT INTO books (title, author, isbn, publisher, publication_year, language, pages, category_id, price, original_price, stock, description, rating_avg, review_count, sold_count, active, created_at, updated_at, cover_key, file_key) 
VALUES ('Collisions: The Origins of the War in Ukraine and the New Global Instability', 'Michael Kimmage', '9780197751794', 'Oxford University Press', 2024, 'en', NULL, (SELECT id FROM categories WHERE name = 'History, Politics & International Relations'), 300000, 390000, 100, 'Tác phẩm "Collisions: The Origins of the War in Ukraine and the New Global Instability" đi sâu vào chủ đề lịch sử hiện đại, phân tích địa chính trị và nguồn gốc của cuộc xung đột vũ trang nghiêm trọng tại Ukraine. Về nội dung chính, cuốn sách mổ xẻ những nguyên nhân sâu xa dẫn đến quyết định đưa quân vào Ukraine của Tổng thống Nga Vladimir Putin vào tháng 2 năm 2022. Tác giả Michael Kimmage phân tích các luồng tư tưởng lịch sử, các sự kiện chính trị và sự biến chuyển trong quan hệ quốc tế từ giai đoạn 2008 đến nay, tập trung vào mối quan hệ phức tạp giữa Hoa Kỳ, châu Âu, Nga và Trung Quốc. Nội dung sách đánh giá chi tiết các chiến lược ngoại giao của các đời tổng thống Mỹ, sự trỗi dậy của tư tưởng bảo thủ tại Nga, cũng như khát vọng của người dân Ukraine về một nhà nước độc lập gắn kết với phương Tây. Sự va chạm giữa các hệ tư tưởng đã tạo nên bối cảnh bất ổn toàn cầu mới. Đối tượng phù hợp của cuốn sách là những độc giả quan tâm đến quan hệ quốc tế, lịch sử chính trị đương đại, các nhà phân tích chiến lược và sinh viên chuyên ngành ngoại giao. Giá trị của cuốn sách là cung cấp một cái nhìn đa chiều, khách quan và có hệ thống, giúp người đọc thấu hiểu được mối liên kết giữa quyền lực, nỗi sợ hãi và hệ tư tưởng trong việc định hình cục diện thế giới.', 0, 0, 0, true, now(), now(), 'Collisions_The_Origins_of_t.png', 'Collisions_The_Origins_of_t.pdf') ON CONFLICT (isbn) WHERE isbn IS NOT NULL DO NOTHING;


INSERT INTO books (title, author, isbn, publisher, publication_year, language, pages, category_id, price, original_price, stock, description, rating_avg, review_count, sold_count, active, created_at, updated_at, cover_key, file_key) 
VALUES ('Đắc Nhân Tâm (How to Win Friends & Influence People)', 'Dale Carnegie', NULL, 'Nhà Xuất Bản Trẻ', 2008, 'vi', NULL, (SELECT id FROM categories WHERE name = 'Psychology & Self-Help'), 315000, 409500, 100, 'Cuốn sách "Đắc Nhân Tâm (How to Win Friends & Influence People)" khai thác chủ đề kỹ năng giao tiếp, nghệ thuật đối nhân xử thế và thu phục lòng người để đạt được thành công viên mãn. Về nội dung chính, đây là một cẩm nang kinh điển hướng dẫn người đọc cách thiết lập và duy trì các mối quan hệ xã hội tốt đẹp. Nội dung sách đúc kết những nguyên tắc vàng trong ứng xử như: không chỉ trích hay than phiền, thành thật khen ngợi người khác, biết lắng nghe một cách chân thành, ghi nhớ tên người đối diện, và luôn nở nụ cười thân thiện. Tác giả Dale Carnegie sử dụng vô số những câu chuyện thực tế để chứng minh rằng nhu cầu sâu sắc nhất của con người là khao khát được cảm thấy mình quan trọng. Sách hướng dẫn cách giải quyết tranh cãi bằng cách tránh né nó, cách thuyết phục người khác đồng thuận mà không gây ra sự oán giận, và cách thừa nhận sai lầm của bản thân. Đối tượng phù hợp vô cùng rộng lớn, từ học sinh, sinh viên, người đi làm cho đến các nhà quản lý, doanh nhân và bất kỳ ai muốn cải thiện kỹ năng sống. Giá trị của tác phẩm mang tính ứng dụng vượt thời gian, giúp độc giả hoàn thiện nhân cách, xây dựng sự tự tin, tạo dựng thiện cảm và củng cố nền tảng vững chắc cho cả hạnh phúc cá nhân lẫn thành công trong sự nghiệp.', 0, 0, 0, true, now(), now(), 'Dac_Nhan_Tam_Dale_Carnegie.png', 'Dac_Nhan_Tam_Dale_Carnegie.pdf') ;


INSERT INTO books (title, author, isbn, publisher, publication_year, language, pages, category_id, price, original_price, stock, description, rating_avg, review_count, sold_count, active, created_at, updated_at, cover_key, file_key) 
VALUES ('Database Internals: A Deep Dive into How Distributed Data Systems Work', 'Alex Petrov', '9781492040347', 'O''Reilly Media, Inc.', 2019, 'en', NULL, (SELECT id FROM categories WHERE name = 'Technology & Computing'), 330000, 429000, 100, 'Cuốn sách "Database Internals: A Deep Dive into How Distributed Data Systems Work" khai thác chủ đề cấu trúc bên trong của cơ sở dữ liệu, các thuật toán lưu trữ và cách thức hoạt động của hệ thống dữ liệu phân tán. Về nội dung chính, tác phẩm là một hành trình đi sâu vào phần lõi của các hệ thống cơ sở dữ liệu hiện đại, giải phẫu cách thức chúng lưu trữ và phân phối dữ liệu. Nội dung được chia làm hai phần chính: động cơ lưu trữ (Storage Engines) và hệ thống phân tán (Distributed Systems). Tác giả trình bày cực kỳ chi tiết về các cấu trúc dữ liệu cơ bản như B-Tree, kiến trúc LSM-Tree, định dạng tệp tin nhị phân, phân trang, và quản lý bộ nhớ. Ở phần hệ thống phân tán, sách giải thích các khái niệm phức tạp như thuật toán đồng thuận (consensus), bầu chọn thủ lĩnh (leader election), các mô hình nhất quán dữ liệu và các giao thức sao chép (replication) giữa các máy chủ. Đối tượng phù hợp của cuốn sách là các kỹ sư phần mềm backend, kỹ sư cơ sở hạ tầng (infrastructure engineers), quản trị viên cơ sở dữ liệu và sinh viên chuyên ngành khoa học máy tính muốn hiểu sâu về cách thức hoạt động của các công cụ họ đang sử dụng. Giá trị cốt lõi của cuốn sách là mang lại nền tảng kiến thức vững chắc, lấp đầy khoảng trống giữa lý thuyết hàn lâm và mã nguồn thực tế, giúp các kỹ sư đưa ra các quyết định thiết kế chính xác và khắc phục sự cố hệ thống hiệu quả.', 0, 0, 0, true, now(), now(), 'Database_Internals_A_Deep-D.png', 'Database_Internals_A_Deep-D.pdf') ON CONFLICT (isbn) WHERE isbn IS NOT NULL DO NOTHING;


INSERT INTO books (title, author, isbn, publisher, publication_year, language, pages, category_id, price, original_price, stock, description, rating_avg, review_count, sold_count, active, created_at, updated_at, cover_key, file_key) 
VALUES ('Database Systems: Design, Implementation, and Management', 'Carlos Coronel, Steven Morris', NULL, 'Cengage Learning', 2019, 'en', NULL, (SELECT id FROM categories WHERE name = 'Technology & Computing'), 345000, 448500, 100, 'Chủ đề: Thiết kế, triển khai và quản trị hệ thống cơ sở dữ liệu, từ các mô hình quan hệ truyền thống đến các công nghệ dữ liệu hiện đại.

Nội dung chính: Cuốn sách cung cấp một cái nhìn toàn diện và chi tiết về toàn bộ vòng đời của hệ thống cơ sở dữ liệu. Các chương trải dài từ nền tảng cơ bản như mô hình dữ liệu, thiết kế khái niệm (mô hình ERD), chuẩn hóa bảng (normalization), cho đến các kỹ thuật nâng cao bao gồm ngôn ngữ truy vấn có cấu trúc (SQL), quản lý giao dịch, kiểm soát đồng thời và tối ưu hóa hiệu suất truy vấn. Ngoài ra, sách còn đề cập sâu đến các hệ thống phân tán, kho dữ liệu (Data Warehouse), Business Intelligence (BI), dữ liệu lớn (Big Data) và các công nghệ NoSQL (như MongoDB, Neo4j), cũng như vai trò quản trị và bảo mật cơ sở dữ liệu của một DBA.

Đối tượng phù hợp: Sinh viên đại học chuyên ngành công nghệ thông tin, kỹ sư phần mềm, nhà thiết kế cơ sở dữ liệu, quản trị viên cơ sở dữ liệu (DBA) và các nhà quản lý muốn nắm bắt kiến thức từ cơ bản đến chuyên sâu.

Giá trị của cuốn sách: Sách mang lại sự cân bằng hoàn hảo giữa lý thuyết nền tảng và thực hành ứng dụng. Nó nhấn mạnh rằng một ứng dụng tốt không thể được xây dựng trên một thiết kế tồi, cung cấp cho người đọc các nguyên tắc thiết kế thực tế để xây dựng những hệ thống lưu trữ dữ liệu an toàn, hiệu quả, đáp ứng yêu cầu khắt khe của doanh nghiệp hiện đại.', 0, 0, 0, true, now(), now(), 'Database_Systems_Design_Im.png', 'Database_Systems_Design_Im.pdf') ;


INSERT INTO books (title, author, isbn, publisher, publication_year, language, pages, category_id, price, original_price, stock, description, rating_avg, review_count, sold_count, active, created_at, updated_at, cover_key, file_key) 
VALUES ('Designing Machine Learning Systems: An Iterative Process for Production-Ready Applications', 'Chip Huyen', '9781098107963', 'O''Reilly Media, Inc.', 2022, 'en', NULL, (SELECT id FROM categories WHERE name = 'Technology & Computing'), 360000, 468000, 100, 'Chủ đề: Thiết kế, xây dựng và triển khai các hệ thống học máy (Machine Learning) có khả năng mở rộng và đáng tin cậy trong môi trường sản xuất thực tế.

Nội dung chính: Tác giả Chip Huyen trình bày một quy trình lặp đi lặp lại (iterative process) để phát triển hệ thống học máy. Sách đi sâu vào các khía cạnh kỹ thuật dữ liệu (data engineering) như định dạng dữ liệu, xử lý hàng loạt và luồng (batch vs. stream processing), kỹ thuật tạo đặc trưng (feature engineering), và các chiến lược xử lý dữ liệu thiếu hoặc mất cân bằng (class imbalance). Bên cạnh đó, tác giả còn hướng dẫn chi tiết về việc phát triển mô hình, đánh giá ngoại tuyến, chiến lược triển khai trực tuyến, phát hiện và xử lý sự dịch chuyển phân phối dữ liệu (data distribution shifts), học liên tục (continual learning) và các công cụ cơ sở hạ tầng MLOps.

Đối tượng phù hợp: Kỹ sư học máy (ML engineers), nhà khoa học dữ liệu (data scientists), kỹ sư dữ liệu và các nhà quản lý kỹ thuật muốn áp dụng học máy vào giải quyết các bài toán thực tiễn của doanh nghiệp.

Giá trị của cuốn sách: Khác với nhiều tài liệu chỉ tập trung vào thuật toán nghiên cứu, cuốn sách mang lại góc nhìn toàn cảnh (holistic approach) về toàn bộ hệ sinh thái MLOps. Nó giúp độc giả hiểu rõ cách tối ưu hóa không chỉ độ chính xác của mô hình mà còn là tính khả dụng, độ tin cậy, khả năng bảo trì và khả năng thích ứng của hệ thống khi đối mặt với dữ liệu thực tế luôn biến đổi.', 0, 0, 0, true, now(), now(), 'Designing_Machine_Learning.png', 'Designing_Machine_Learning.pdf') ON CONFLICT (isbn) WHERE isbn IS NOT NULL DO NOTHING;


INSERT INTO books (title, author, isbn, publisher, publication_year, language, pages, category_id, price, original_price, stock, description, rating_avg, review_count, sold_count, active, created_at, updated_at, cover_key, file_key) 
VALUES ('Direct Social Work Practice: Theory and Skills', 'Dean H. Hepworth, Ronald H. Rooney, Glenda Dewberry Rooney, Kimberly Strom-Gottfried', NULL, 'Cengage Learning', 2017, 'en', NULL, (SELECT id FROM categories WHERE name = 'Social Sciences'), 375000, 487500, 100, 'Chủ đề: Các kỹ năng, lý thuyết và nguyên tắc giao tiếp cốt lõi trong thực hành công tác xã hội trực tiếp với thân chủ.

Nội dung chính: Thông qua các tài liệu trích xuất, cuốn sách hướng dẫn người thực hành cách tiến hành các buổi làm việc trực tiếp với thân chủ một cách chuyên nghiệp. Nội dung bao gồm việc sử dụng các câu hỏi mở để thu thập thông tin một cách khách quan, đánh giá nhận thức của thân chủ về lý do họ cần sự trợ giúp. Sách nhấn mạnh tầm quan trọng của việc sử dụng ngôn ngữ rõ ràng, dễ hiểu để giải thích mục đích và rủi ro của dịch vụ. Hơn nữa, tài liệu cung cấp các quy tắc khắt khe về việc ghi chép hồ sơ, yêu cầu người thực hành phân biệt rõ giữa sự kiện quan sát được và ý kiến cá nhân, tránh sử dụng thuật ngữ chuyên ngành khó hiểu hay các chẩn đoán chưa được xác minh. Sách còn đi kèm thang điểm đánh giá mức độ giao tiếp (từ kém đến xuất sắc).

Đối tượng phù hợp: Nhân viên công tác xã hội, nhà tư vấn tâm lý, chuyên gia thực hành lâm sàng và sinh viên đang theo học ngành công tác xã hội hoặc tâm lý học.

Giá trị của cuốn sách: Sách là một cẩm nang thiết thực giúp nâng cao năng lực lâm sàng và kỹ năng giao tiếp. Bằng cách cung cấp các thang đánh giá và hướng dẫn đạo đức cụ thể, nó đảm bảo người thực hành có thể cung cấp các dịch vụ hỗ trợ chất lượng cao, minh bạch và tôn trọng quyền lợi của thân chủ.', 0, 0, 0, true, now(), now(), 'Direct_Social_Work_Practice.png', 'Direct_Social_Work_Practice.pdf') ;


INSERT INTO books (title, author, isbn, publisher, publication_year, language, pages, category_id, price, original_price, stock, description, rating_avg, review_count, sold_count, active, created_at, updated_at, cover_key, file_key) 
VALUES ('Essential Math for AI: Next-Level Mathematics for Efficient and Successful AI Systems', 'Hala Nelson', '9781098107635', 'O''Reilly Media, Inc.', 2023, 'en', NULL, (SELECT id FROM categories WHERE name = 'Science & Mathematics'), 390000, 507000, 100, 'Chủ đề: Nền tảng toán học ứng dụng cho trí tuệ nhân tạo (AI), xử lý ngôn ngữ tự nhiên (NLP), tài chính và nghiên cứu hoạt động.

Nội dung chính: Sách giải mã các công cụ toán học đằng sau các hệ thống AI hiện đại mà không sa đà vào việc viết mã lập trình. Nội dung trọng tâm bao gồm cách véc-tơ hóa dữ liệu phi cấu trúc (chuyển đổi tài liệu văn bản thành các véc-tơ số), các mô hình ngôn ngữ tự nhiên như Word2Vec, Transformer, và các mạng nơ-ron hồi quy xử lý dữ liệu chuỗi thời gian. Cuốn sách cũng thảo luận về các bài toán tối ưu hóa rời rạc và nghiên cứu hoạt động (như bài toán người bán hàng, cân bằng tải mạng lưới). Cuối cùng, sách dành một phần quan trọng để bàn về các thách thức đạo đức của AI, cách khắc phục thành kiến (bias) trong véc-tơ từ và nhấn mạnh sự cần thiết của dữ liệu chất lượng cao.

Đối tượng phù hợp: Cấp quản lý muốn tích hợp AI vào chiến lược kinh doanh, chuyên viên phân tích dữ liệu, và những cá nhân quan tâm đến sự minh bạch, rủi ro cũng như khía cạnh đạo đức của các thuật toán trí tuệ nhân tạo.

Giá trị của cuốn sách: Cuốn sách thu hẹp khoảng cách giữa lý thuyết toán học trừu tượng và các ứng dụng thực tế trong khoa học máy tính. Nó giúp người đọc hiểu thấu đáo cơ chế hoạt động thực sự bên trong (inner workings) của các hệ thống AI, từ đó trang bị cho họ kiến thức vững chắc để tích hợp công nghệ một cách an toàn, công bằng và có trách nhiệm.', 0, 0, 0, true, now(), now(), 'Essential_Math_for_AI_Next.png', 'Essential_Math_for_AI_Next.pdf') ON CONFLICT (isbn) WHERE isbn IS NOT NULL DO NOTHING;


INSERT INTO books (title, author, isbn, publisher, publication_year, language, pages, category_id, price, original_price, stock, description, rating_avg, review_count, sold_count, active, created_at, updated_at, cover_key, file_key) 
VALUES ('FastAPI Cookbook: Develop high-performance APIs and web applications with Python', 'Giunio De Luca', '9781805127857', 'Packt Publishing Ltd.', 2024, 'en', NULL, (SELECT id FROM categories WHERE name = 'Technology & Computing'), 405000, 526500, 100, 'Chủ đề: Phát triển các giao diện lập trình ứng dụng (API) và ứng dụng web hiệu suất cao bằng framework FastAPI của Python.

Nội dung chính: Sách hoạt động như một cẩm nang công thức (cookbook) cung cấp các giải pháp thực tế để làm việc với FastAPI. Bắt đầu từ những bước thiết lập môi trường cơ bản, sách đi sâu vào cách xử lý dữ liệu, thực hiện các thao tác CRUD với cơ sở dữ liệu SQL (thông qua SQLAlchemy) và NoSQL (MongoDB). Người đọc sẽ được hướng dẫn cách thiết kế RESTful API, sử dụng thư viện Pydantic để xác thực và tuần tự hóa dữ liệu. Các chương nâng cao bao gồm triển khai cơ chế xác thực và phân quyền (OAuth2, JWT), kiểm thử hiệu suất, gỡ lỗi, và ứng dụng WebSockets cho giao tiếp thời gian thực. Hơn nữa, sách còn hướng dẫn tích hợp các mô hình Machine Learning và xây dựng trợ lý AI (ứng dụng RAG) sử dụng công cụ LangChain.

Đối tượng phù hợp: Lập trình viên Python từ trình độ trung cấp đến cao cấp, các nhà phát triển web muốn nâng cao kỹ năng xây dựng API có khả năng mở rộng.

Giá trị của cuốn sách: Mang đến những hướng dẫn thực hành từng bước, giúp các lập trình viên vượt qua rào cản tài liệu phức tạp để tạo ra các ứng dụng sẵn sàng cho môi trường sản xuất (production-ready). Sách trang bị bộ công cụ toàn diện giúp tối ưu hóa hiệu năng, tăng cường bảo mật và mở rộng tính năng hệ thống web hiệu quả.', 0, 0, 0, true, now(), now(), 'FastAPI_Cookbook_Develop_hi.png', 'FastAPI_Cookbook_Develop_hi.pdf') ON CONFLICT (isbn) WHERE isbn IS NOT NULL DO NOTHING;


INSERT INTO books (title, author, isbn, publisher, publication_year, language, pages, category_id, price, original_price, stock, description, rating_avg, review_count, sold_count, active, created_at, updated_at, cover_key, file_key) 
VALUES ('Flow Architectures: The Future of Streaming and Event-Driven Integration', 'James Urquhart', '9781492075899', 'O''Reilly Media, Inc.', 2021, 'en', NULL, (SELECT id FROM categories WHERE name = 'Technology & Computing'), 420000, 546000, 100, 'Chủ đề: Kiến trúc phần mềm hướng sự kiện (event-driven), truyền phát dữ liệu (streaming) và tích hợp hệ thống trong nền kinh tế kỹ thuật số.

Nội dung chính: Cuốn sách khám phá tương lai của việc tích hợp phần mềm thông qua các luồng dữ liệu (flow). Tác giả phân tích lý do doanh nghiệp cần chuyển đổi số và áp dụng luồng sự kiện để giảm thời gian chờ đợi (lead time), tăng cường hiệu quả vận hành và cá nhân hóa trải nghiệm khách hàng. Nội dung bao gồm việc sử dụng các công cụ lập bản đồ chiến lược (Wardley Mapping, Promise Theory) để phân tích chuỗi giá trị tích hợp, đánh giá các công nghệ hiện tại (như nền tảng Kafka, Flink, Message Queues) và các mô hình tích hợp cốt lõi (Collector, Distributor, Signal, Facilitator). Từ đó, sách chỉ ra cách các hệ thống có thể phản ứng theo thời gian thực trước những thay đổi của hệ sinh thái phần mềm.

Đối tượng phù hợp: Kiến trúc sư phần mềm, chuyên gia tích hợp hệ thống, quản lý sản phẩm và các nhà lãnh đạo doanh nghiệp muốn chuẩn bị hạ tầng công nghệ cho tương lai.

Giá trị của cuốn sách: Không chỉ giới thiệu về mặt công nghệ, sách còn mang tính chiến lược cao, giúp người đọc nhận thức rõ tầm quan trọng của việc chia sẻ dữ liệu liên tổ chức (World Wide Flow). Sách cung cấp tầm nhìn sâu sắc để doanh nghiệp thiết kế các hệ thống linh hoạt, tối ưu chi phí và sẵn sàng thích ứng với xu hướng xử lý dữ liệu thời gian thực.', 0, 0, 0, true, now(), now(), 'Flow_Architectures_The_Futu.png', 'Flow_Architectures_The_Futu.pdf') ON CONFLICT (isbn) WHERE isbn IS NOT NULL DO NOTHING;


INSERT INTO books (title, author, isbn, publisher, publication_year, language, pages, category_id, price, original_price, stock, description, rating_avg, review_count, sold_count, active, created_at, updated_at, cover_key, file_key) 
VALUES ('Foundations of Scalable Systems: Designing Distributed Architectures', 'Ian Gorton', '9781098106065', 'O''Reilly Media, Inc.', 2022, 'en', NULL, (SELECT id FROM categories WHERE name = 'Technology & Computing'), 435000, 565500, 100, 'Chủ đề: Nguyên tắc thiết kế, kiến trúc và công nghệ nền tảng để xây dựng các hệ thống phần mềm phân tán có khả năng mở rộng (scalable systems).

Nội dung chính: Tác giả Ian Gorton cung cấp kiến thức nền tảng để giải quyết thách thức khi lượng người dùng và dữ liệu tăng vọt. Sách bao quát các nguyên lý cốt lõi của tính toán phân tán và lập trình đồng thời (concurrency), bao gồm xử lý đa luồng (threads), tình trạng bế tắc (deadlocks) và quản lý trạng thái. Nội dung đi sâu vào kiến trúc dịch vụ vi mô (microservices), phân tải (load balancing), và bộ nhớ đệm (caching). Đặc biệt, sách phân tích chi tiết các chiến lược phân phối cơ sở dữ liệu (từ SQL truyền thống đến các hệ thống NoSQL, DynamoDB, MongoDB, Redis), giải quyết bài toán giữa tính nhất quán (consistency) và tính sẵn sàng (availability) thông qua định lý CAP. Cuối cùng, sách thảo luận về các nền tảng xử lý luồng và sự kiện như Apache Kafka và Flink.

Đối tượng phù hợp: Kỹ sư phần mềm, kiến trúc sư hệ thống, sinh viên khoa học máy tính và những người cần phải xây dựng, quản lý các ứng dụng quy mô lớn hướng đến môi trường mạng Internet.

Giá trị của cuốn sách: Đây là tài liệu kết hợp hài hòa giữa lý thuyết hàn lâm và kinh nghiệm thực tiễn. Nó giúp người đọc vượt qua các cạm bẫy thiết kế và "nợ kỹ thuật" (technical debt) bằng cách hiểu rõ những sự đánh đổi (trade-offs) trong kiến trúc, qua đó xây dựng được các hệ thống mạnh mẽ, linh hoạt trong kỷ nguyên điện toán đám mây.', 0, 0, 0, true, now(), now(), 'Foundations_of_Scalable_Sys.png', 'Foundations_of_Scalable_Sys.pdf') ON CONFLICT (isbn) WHERE isbn IS NOT NULL DO NOTHING;


INSERT INTO books (title, author, isbn, publisher, publication_year, language, pages, category_id, price, original_price, stock, description, rating_avg, review_count, sold_count, active, created_at, updated_at, cover_key, file_key) 
VALUES ('Hacking With Python: The Complete Beginner''s Course to Learn Ethical Hacking With Python in 7 Clear-Cut Lessons', 'Alphy Books', NULL, 'Alphy Books', 2016, 'en', NULL, (SELECT id FROM categories WHERE name = 'Technology & Computing'), 450000, 585000, 100, 'Chủ đề: Sử dụng ngôn ngữ lập trình Python trong lĩnh vực an ninh mạng, tập trung vào kỹ thuật thu thập thông tin và thử nghiệm thâm nhập.

Nội dung chính: Cuốn sách là tài liệu hướng dẫn chi tiết về các phương pháp thu thập dữ liệu từ hệ thống máy tính của mục tiêu. Trong các đoạn trích xuất, tác giả tập trung vào việc viết mã Python để tương tác với hệ điều hành Windows (cụ thể là Windows 7). Nội dung bao gồm cách sử dụng các module tích hợp sẵn của Python (như winreg) để đọc và duyệt qua các khóa (keys) cũng như giá trị (values) trong Windows Registry. Sách hướng dẫn chi tiết cách viết các hàm thu thập danh sách subkey, trích xuất dữ liệu phần cứng mạng, định dạng địa chỉ vật lý (MAC address) và chuyển đổi định dạng thời gian của hệ thống (filetime) sang định dạng ngày tháng có thể đọc được nhằm phục vụ mục đích phân tích.

Đối tượng phù hợp: Những người mới bắt đầu tìm hiểu về tấn công có đạo đức (ethical hacking), các lập trình viên Python, nhà phân tích bảo mật và quản trị viên hệ thống muốn nắm bắt cơ chế hoạt động của hệ điều hành.

Giá trị của cuốn sách: Cung cấp các ví dụ mã nguồn rõ ràng, dễ hiểu giúp người học nhanh chóng áp dụng Python vào thực tiễn bảo mật. Sách trang bị những kỹ năng nền tảng quan trọng giúp độc giả tự xây dựng các công cụ trinh sát và thu thập thông tin tùy chỉnh, làm cơ sở để tiến tới các kỹ năng kiểm thử bảo mật nâng cao hơn.', 0, 0, 0, true, now(), now(), 'Hacking_Hacking_With_Python.png', 'Hacking_Hacking_With_Python.pdf') ;


INSERT INTO books (title, author, isbn, publisher, publication_year, language, pages, category_id, price, original_price, stock, description, rating_avg, review_count, sold_count, active, created_at, updated_at, cover_key, file_key) 
VALUES ('Improving Your Memory', 'David Thomas', '9780756634179', 'DK Publishing', 2008, 'en', 72, (SELECT id FROM categories WHERE name = 'Psychology & Self-Help'), 465000, 604500, 100, 'Chủ đề: Rèn luyện và cải thiện khả năng của trí nhớ. Nội dung chính: Cuốn sách giải thích chi tiết cách bộ não và trí nhớ hoạt động (bao gồm trí nhớ ngắn hạn và dài hạn), đồng thời bác bỏ định kiến cho rằng trí nhớ tất yếu suy giảm theo tuổi tác. Tác giả cung cấp một loạt các phương pháp và kỹ thuật rèn luyện trí nhớ cụ thể như hệ thống chữ cái ngữ âm (Phonetic Letter Technique), phương pháp hành trình (Journey Technique), sử dụng sơ đồ tư duy (Mind Maps) và các nguyên tắc tạo hình ảnh (Image Creation Principles). Nhờ đó, người đọc có thể dễ dàng ghi nhớ tên người, con số, danh sách và ngày tháng. Đối tượng phù hợp: Học sinh, sinh viên cần ghi nhớ kiến thức, người đi làm muốn tăng hiệu suất công việc, và bất kỳ ai muốn nâng cao sự minh mẫn. Giá trị: Cung cấp hệ thống bài tập thực hành rõ ràng, giúp người đọc xây dựng sự tự tin trong giao tiếp xã hội và công việc thông qua việc tận dụng tối đa tiềm năng của bộ não.', 0, 0, 0, true, now(), now(), 'Improving_Your_Memory.png', 'Improving_Your_Memory.pdf') ON CONFLICT (isbn) WHERE isbn IS NOT NULL DO NOTHING;


INSERT INTO books (title, author, isbn, publisher, publication_year, language, pages, category_id, price, original_price, stock, description, rating_avg, review_count, sold_count, active, created_at, updated_at, cover_key, file_key) 
VALUES ('J. Christoph Amberger''s Hot Trading Secrets: How to Get In and Out of the Market with Huge Gains in Any Climate', 'J. Christoph Amberger', '9780471738725', 'John Wiley & Sons, Inc.', 2006, 'en', 302, (SELECT id FROM categories WHERE name = 'Business & Finance'), 480000, 624000, 100, 'Chủ đề: Chiến lược giao dịch chứng khoán linh hoạt trong mọi điều kiện thị trường. Nội dung chính: Cuốn sách giới thiệu Lý thuyết Thị trường Động (Dynamic Market Theory), nhấn mạnh rằng các nhà giao dịch không cần quan tâm thị trường đang lên hay xuống mà vẫn có thể kiếm lợi nhuận nếu biết cách đọc các tín hiệu. Sách chia sẻ các bí quyết giao dịch cụ thể như tận dụng tính chu kỳ theo mùa, chỉ báo tăng đột biến khối lượng giao dịch (Volume Spike Indicator) nhằm theo dấu dòng tiền của những người trong cuộc một cách hợp pháp, giao dịch dựa trên tin tức (Extreme Volatility), và các mô hình biểu đồ nến (Doji Master). Đối tượng phù hợp: Các nhà đầu tư cá nhân, nhà giao dịch chứng khoán từ nghiệp dư đến chuyên nghiệp đang tìm kiếm các chiến lược lướt sóng, giao dịch ngắn hạn để tối đa hóa lợi nhuận. Giá trị: Mang lại cái nhìn thực tế về cách dòng tiền hoạt động đằng sau các thị trường tài chính, cung cấp công cụ để nhà đầu tư tự kiểm soát rủi ro và tìm kiếm cơ hội sinh lời lớn từ những biến động nhanh chóng của thị trường.', 0, 0, 0, true, now(), now(), 'J._Christoph_Ambergers_Hot.png', 'J._Christoph_Ambergers_Hot.pdf') ON CONFLICT (isbn) WHERE isbn IS NOT NULL DO NOTHING;


INSERT INTO books (title, author, isbn, publisher, publication_year, language, pages, category_id, price, original_price, stock, description, rating_avg, review_count, sold_count, active, created_at, updated_at, cover_key, file_key) 
VALUES ('Kafka bên bờ biển', 'Haruki Murakami', NULL, 'Nhà xuất bản Văn học', 2007, 'vi', NULL, (SELECT id FROM categories WHERE name = 'Fiction & Literature'), 495000, 643500, 100, 'Chủ đề: Hành trình trưởng thành, cái tôi vô thức và những yếu tố siêu thực đan xen trong thế giới hiện đại. Nội dung chính: Tác phẩm là hai câu chuyện đan xen độc đáo: một bên là cậu bé mười lăm tuổi tự xưng là Kafka Tamura, bỏ nhà ra đi để trốn tránh một lời nguyền tàn khốc của người cha, dạt đến một thư viện tư nhân ở Takamatsu; bên kia là ông lão Nakata, người bị thiểu năng trí tuệ sau một tai nạn bí ẩn thời chiến tranh nhưng lại có khả năng nói chuyện với mèo và linh cảm các hiện tượng siêu nhiên. Hai con người xa lạ dần bước vào một mạng lưới định mệnh kết nối họ lại với nhau qua những sự kiện kỳ ảo như mưa cá, mưa đỉa và những hồn ma người sống. Đối tượng phù hợp: Độc giả yêu thích văn học đương đại Nhật Bản, say mê chủ nghĩa hiện thực huyền ảo, và những ai thích khám phá triết lý nhân sinh ẩn giấu qua các biểu tượng phức tạp. Giá trị: Tác phẩm mang đến trải nghiệm văn học sâu sắc, gợi mở sự suy ngẫm về sự song hành giữa thiện và ác, giữa số phận và lựa chọn cá nhân, đồng thời khắc họa tuyệt đẹp sức mạnh của ký ức và thế giới tiềm thức.', 0, 0, 0, true, now(), now(), 'Kafka_ben_bo_bien.png', 'Kafka_ben_bo_bien.pdf') ;


INSERT INTO books (title, author, isbn, publisher, publication_year, language, pages, category_id, price, original_price, stock, description, rating_avg, review_count, sold_count, active, created_at, updated_at, cover_key, file_key) 
VALUES ('Keep Your Brain Alive: 83 Neurobic Exercises to Help Prevent Memory Loss and Increase Mental Fitness', 'Lawrence C. Katz, Manning Rubin', '9780761110521', 'Workman Publishing Company', 1999, 'en', 148, (SELECT id FROM categories WHERE name = 'Health & Fitness'), 510000, 663000, 100, 'Chủ đề: Thể dục trí não (Neurobics) nhằm ngăn ngừa suy giảm trí nhớ và tăng cường sự minh mẫn. Nội dung chính: Cuốn sách bác bỏ quan niệm rằng bộ não suy tàn theo tuổi tác, thay vào đó giới thiệu một chương trình tập luyện khoa học gọi là Neurobics. Phương pháp này sử dụng tất cả năm giác quan cùng với cảm xúc theo những cách mới mẻ, phá vỡ thói quen hàng ngày nhằm kích thích các tế bào thần kinh sản sinh ra dưỡng chất tự nhiên (neurotrophins) giúp phát triển mạng lưới liên kết não bộ. Sách cung cấp 83 bài tập thực tế áp dụng trong các hoạt động thường nhật như lúc thức dậy, đi làm, ăn uống hay nghỉ ngơi. Đối tượng phù hợp: Bất kỳ ai quan tâm đến sức khỏe tâm thần, những người ở độ tuổi trung niên hoặc cao tuổi muốn duy trì trí nhớ, cũng như những người trẻ muốn xây dựng thói quen sống tích cực cho não bộ. Giá trị: Cung cấp giải pháp đơn giản, không cần dùng thuốc, giúp con người chủ động tự chăm sóc sức khỏe tinh thần thông qua việc thay đổi những thói quen nhỏ nhất trong lối sống thường ngày.', 0, 0, 0, true, now(), now(), 'Keep_Your_Brain_Alive_83_Ne.png', 'Keep_Your_Brain_Alive_83_Ne.pdf') ON CONFLICT (isbn) WHERE isbn IS NOT NULL DO NOTHING;


INSERT INTO books (title, author, isbn, publisher, publication_year, language, pages, category_id, price, original_price, stock, description, rating_avg, review_count, sold_count, active, created_at, updated_at, cover_key, file_key) 
VALUES ('LangChain Crash Course: Build OpenAI LLM powered Apps', 'Greg Lim', NULL, NULL, 2023, 'en', NULL, (SELECT id FROM categories WHERE name = 'Technology & Computing'), 525000, 682500, 100, 'Chủ đề: Hướng dẫn xây dựng ứng dụng trí tuệ nhân tạo dựa trên mô hình ngôn ngữ lớn (LLM) thông qua framework LangChain. Nội dung chính: Sách cung cấp lộ trình thực hành ngắn gọn để làm quen với LangChain, giải thích cách công cụ này khắc phục hạn chế của các mô hình LLM như ChatGPT (dữ liệu lỗi thời, không có khả năng truy cập thông tin nội bộ) bằng cách kết nối với các nguồn dữ liệu bên ngoài. Các chương bao gồm từ việc thiết lập cơ bản, kết nối với OpenAI LLM, xây dựng các mẫu prompt (Prompt Templates), tạo chuỗi lệnh (Chains) và các tác tử (Agents). Sách hướng dẫn chi tiết cách tạo ứng dụng thực tế như máy tạo bài viết Medium, chatbot truy vấn nội dung từ tài liệu PDF, văn bản, hoặc video YouTube. Đối tượng phù hợp: Lập trình viên, kỹ sư phần mềm, và những người đam mê AI muốn tích hợp sức mạnh của OpenAI GPT vào các dự án thực tế. Giá trị: Sách mang tính thực tiễn cao, giúp người đọc nắm bắt nhanh chóng công nghệ LangChain để tự xây dựng các quy trình tự động hóa AI, giải quyết bài toán truy xuất thông tin cá nhân và doanh nghiệp.', 0, 0, 0, true, now(), now(), 'LangChain_Crash_Course_Buil.png', 'LangChain_Crash_Course_Buil.pdf') ;


INSERT INTO books (title, author, isbn, publisher, publication_year, language, pages, category_id, price, original_price, stock, description, rating_avg, review_count, sold_count, active, created_at, updated_at, cover_key, file_key) 
VALUES ('Learning Domain-Driven Design: Aligning Software Architecture and Business Strategy', 'Vlad Khononov', '9781098100131', 'O''Reilly Media, Inc.', 2021, 'en', 312, (SELECT id FROM categories WHERE name = 'Technology & Computing'), 540000, 702000, 100, 'Chủ đề: Các nguyên tắc và thực tiễn của Thiết kế Hướng Tên miền (Domain-Driven Design - DDD) trong kiến trúc phần mềm. Nội dung chính: Cuốn sách giải quyết sự phức tạp trong việc xây dựng phần mềm bằng cách căn chỉnh thiết kế hệ thống sát với chiến lược và nhu cầu kinh doanh thực tế. Sách chia thành các phần: Thiết kế chiến lược (Strategic Design) giúp phân tích lĩnh vực kinh doanh, chia tách các hệ thống con (Core, Generic, Supporting subdomains) và sử dụng Ngôn ngữ chung (Ubiquitous Language) để kết nối chuyên gia nghiệp vụ với kỹ sư. Thiết kế chiến thuật (Tactical Design) đưa ra các mẫu triển khai logic nghiệp vụ như Transaction Script, Active Record, Domain Model, Event-Sourced Domain Model. Cuối cùng là cách áp dụng DDD vào các kiến trúc hiện đại như Microservices, Event-Driven Architecture, hay Data Mesh. Đối tượng phù hợp: Kỹ sư phần mềm, kiến trúc sư phần mềm, và các nhà quản lý kỹ thuật mong muốn kiến trúc linh hoạt, dễ bảo trì. Giá trị: Cung cấp công cụ và quy tắc kinh nghiệm (heuristics) rõ ràng giúp chuyển hóa DDD thành các kỹ thuật dễ tiếp cận, khắc phục sự sai lệch giữa mã nguồn và yêu cầu kinh doanh.', 0, 0, 0, true, now(), now(), 'Learning_Domain-Driven_Desi.png', 'Learning_Domain-Driven_Desi.pdf') ON CONFLICT (isbn) WHERE isbn IS NOT NULL DO NOTHING;


INSERT INTO books (title, author, isbn, publisher, publication_year, language, pages, category_id, price, original_price, stock, description, rating_avg, review_count, sold_count, active, created_at, updated_at, cover_key, file_key) 
VALUES ('Long/Short Market Dynamics: Trading Strategies for Today''s Markets', 'Clive M. Corcoran', '9780470057285', 'John Wiley & Sons Ltd', 2007, 'en', 349, (SELECT id FROM categories WHERE name = 'Business & Finance'), 555000, 721500, 100, 'Chủ đề: Động lực thị trường và các chiến lược giao dịch mua/bán khống trong môi trường tài chính hiện đại. Nội dung chính: Cuốn sách phân tích sâu sắc cấu trúc và dòng chảy của các thị trường vốn, chỉ ra sự thay đổi do giao dịch thuật toán và các công cụ phái sinh. Tác giả trình bày các kỹ thuật phân tích tiên tiến để nhận diện cơ hội giao dịch, tập trung vào việc đọc các chỉ báo bất đồng (dissonance), các mẫu hình phá vỡ (breakout), khoảng trống giá (gaps) hoặc sự biến động. Sách làm rõ sự khác biệt và rủi ro giữa giao dịch hội tụ (convergence trading) và các chiến lược thống kê, đồng thời cung cấp phương pháp quản lý rủi ro, xác định quy mô vị thế, và tối ưu hóa danh mục đầu tư lướt sóng (long/short). Đối tượng phù hợp: Các nhà giao dịch chuyên nghiệp, nhà quản lý quỹ phòng hộ, và nhà đầu tư cá nhân có nền tảng phân tích kỹ thuật muốn tìm kiếm lợi nhuận dương (alpha). Giá trị: Mang đến khuôn khổ phân tích cực kỳ thực tiễn, giúp nhà đầu tư nhìn xuyên qua nhiễu loạn thị trường, thiết lập kỷ luật quản lý vốn nghiêm ngặt để sinh tồn và sinh lời mạnh mẽ.', 0, 0, 0, true, now(), now(), 'LongShort_Market_Dynamics_T.png', 'LongShort_Market_Dynamics_T.pdf') ON CONFLICT (isbn) WHERE isbn IS NOT NULL DO NOTHING;


INSERT INTO books (title, author, isbn, publisher, publication_year, language, pages, category_id, price, original_price, stock, description, rating_avg, review_count, sold_count, active, created_at, updated_at, cover_key, file_key) 
VALUES ('Mặc kệ thiên hạ - Sống như người Nhật', 'Mari Tamagawa', NULL, 'Sky Books', NULL, 'vi', NULL, (SELECT id FROM categories WHERE name = 'Psychology & Self-Help'), 570000, 741000, 100, 'Chủ đề: Kỹ năng sống, thấu hiểu tâm lý và giải phóng bản thân khỏi áp lực từ những đánh giá của người khác. Nội dung chính: Tác giả, một chuyên gia tâm lý từng trải qua nhiều biến cố như bị bạo hành và trầm cảm, chia sẻ hành trình phục hồi tinh thần. Cuốn sách phản bác quan niệm tìm kiếm sự xoa dịu (nhờ vả người khác) hay các lời an ủi sáo rỗng, bởi điều đó chỉ khiến con người thêm lệ thuộc. Thay vào đó, tác giả hướng dẫn độc giả dũng cảm đối mặt với cảm giác bất lực (Kosotsuki taiken - rơi xuống tận đáy), từ bỏ lối sống theo quan điểm hay những nhãn dán của người khác. Bằng cách thực hiện các phép thử, tìm kiếm sự tự nhận thức cá nhân qua những thói quen nhỏ như ghi nhật ký, soi gương, người đọc sẽ tìm lại được chính kiến. Đối tượng phù hợp: Những người đang gặp căng thẳng, áp lực, người mắc chứng trầm cảm nhẹ, hoặc bất kỳ ai mệt mỏi vì phải chạy theo kỳ vọng xã hội. Giá trị: Cung cấp lời khuyên tâm lý thực tế, dứt khoát, khơi dậy sức mạnh nội tại để tự chữa lành vết thương tâm hồn và thiết lập cuộc sống tự do.', 0, 0, 0, true, now(), now(), 'Mac_Ke_Thien_Ha_-_Song_Nhu.png', 'Mac_Ke_Thien_Ha_-_Song_Nhu.pdf') ;


INSERT INTO books (title, author, isbn, publisher, publication_year, language, pages, category_id, price, original_price, stock, description, rating_avg, review_count, sold_count, active, created_at, updated_at, cover_key, file_key) 
VALUES ('Muôn kiếp nhân sinh', 'Nguyên Phong', NULL, 'First News', NULL, 'vi', NULL, (SELECT id FROM categories WHERE name = 'Religion & Spirituality'), 585000, 760500, 100, 'Chủ đề: Luân hồi, luật nhân quả và sự thức tỉnh tâm linh của con người cũng như của nhân loại. Nội dung chính: Cuốn sách thuật lại những trải nghiệm tiền kiếp chân thực của Thomas, một doanh nhân thành đạt ở New York. Xuyên suốt tác phẩm là một thước phim đồ sộ, sống động về những kiếp sống kéo dài từ nền văn minh Atlantis huy hoàng nhưng tham lam, cho đến vương triều Ai Cập cổ đại đầy quyền uy của các Pharaoh, và cuối cùng là nước Mỹ hiện đại. Dưới sự dẫn dắt của các bậc hiền triết (như ông Kris), Thomas dần nhận ra rằng vạn vật trong vũ trụ đều chịu sự chi phối chặt chẽ của luật Nhân quả và luật Chu kỳ (Thành - Trụ - Hoại - Diệt). Những kiến thức uyên bác về khoa học, y học, tôn giáo cổ đại đều được đan cài khéo léo để lý giải nguồn gốc và số phận của con người. Đối tượng phù hợp: Độc giả quan tâm đến lĩnh vực tâm linh, triết học phương Đông, các nền văn minh cổ đại, và những ai tìm kiếm sự bình an giữa thế giới biến động. Giá trị: Truyền tải thông điệp thức tỉnh mạnh mẽ về đạo đức, cảnh tỉnh con người về lối sống ích kỷ, mang đến hy vọng chuyển đổi tâm thức.', 0, 0, 0, true, now(), now(), 'Muon_Kiep_Nhan_Sinh.png', 'Muon_Kiep_Nhan_Sinh.pdf') ;


INSERT INTO books (title, author, isbn, publisher, publication_year, language, pages, category_id, price, original_price, stock, description, rating_avg, review_count, sold_count, active, created_at, updated_at, cover_key, file_key) 
VALUES ('Natural Language Processing with Transformers', 'Lewis Tunstall, Leandro von Werra, Thomas Wolf', '9781098103248', 'O''Reilly Media, Inc.', 2022, 'en', NULL, (SELECT id FROM categories WHERE name = 'Technology & Computing'), 600000, 780000, 100, 'Cuốn sách "Natural Language Processing with Transformers" tập trung vào chủ đề xử lý ngôn ngữ tự nhiên (NLP) thông qua việc sử dụng kiến trúc Transformer, một bước đột phá trong học máy. Nội dung chính của sách là hướng dẫn thực hành cách đào tạo và mở rộng các mô hình ngôn ngữ lớn bằng thư viện Hugging Face Transformers dựa trên ngôn ngữ lập trình Python. Sách cung cấp kiến thức chi tiết về nhiều tác vụ như phân loại văn bản, nhận dạng thực thể có tên, trả lời câu hỏi, tóm tắt và tạo văn bản. Ngoài ra, sách còn giải quyết các thách thức thực tế như tinh chỉnh mô hình khi có ít hoặc không có dữ liệu nhãn, tối ưu hóa hiệu suất mô hình trong môi trường sản xuất thông qua kỹ thuật chưng cất, lượng tử hóa và cắt tỉa, cũng như cách đào tạo một mô hình từ đầu. Đối tượng phù hợp của cuốn sách là các nhà khoa học dữ liệu và kỹ sư học máy đã có kiến thức cơ bản về lập trình Python và các khung học sâu như PyTorch hoặc TensorFlow. Giá trị của cuốn sách nằm ở chỗ nó cung cấp các hướng dẫn thực tế, mã nguồn phong phú và kinh nghiệm trực tiếp từ các tác giả là những kỹ sư phát triển thư viện Hugging Face, giúp người đọc nhanh chóng áp dụng kiến thức nghiên cứu vào thực tiễn.', 0, 0, 0, true, now(), now(), 'Natural_Language_Processing.png', 'Natural_Language_Processing.pdf') ON CONFLICT (isbn) WHERE isbn IS NOT NULL DO NOTHING;


INSERT INTO books (title, author, isbn, publisher, publication_year, language, pages, category_id, price, original_price, stock, description, rating_avg, review_count, sold_count, active, created_at, updated_at, cover_key, file_key) 
VALUES ('Bulletproof Setups: 29 Proven Stock Market Training Strategies', 'Matt Giannino', '9781734554007', 'Giannino Products and Services', 2020, 'en', NULL, (SELECT id FROM categories WHERE name = 'Business & Finance'), 615000, 799500, 100, '"Bulletproof Setups" là một tài liệu chuyên sâu về chủ đề giao dịch và phân tích kỹ thuật trên thị trường chứng khoán. Nội dung chính của cuốn sách là trình bày chi tiết 29 chiến lược và mô hình thiết lập giao dịch đã được kiểm chứng, từ các mô hình cơ bản như lấp đầy khoảng trống (gap fill), nến nhấn chìm (engulfing candle) cho đến các mô hình phức tạp hơn như bứt phá kênh giá, nén dải Bollinger, đáy chữ W, hay cốc và tay cầm. Sách nhấn mạnh vào việc nhận diện động lượng thị trường, tìm kiếm các điểm thoái lui (pullback) hợp lý, thiết lập mức dừng lỗ và quản lý tỷ lệ rủi ro/lợi nhuận hiệu quả. Đối tượng phù hợp của cuốn sách bao gồm các nhà giao dịch trong ngày (day trader), nhà giao dịch theo sóng (swing trader) và những nhà đầu tư muốn cải thiện kỹ năng phân tích biểu đồ kỹ thuật. Giá trị cốt lõi mà cuốn sách mang lại là những kinh nghiệm thực chiến được đúc kết từ hơn 10.000 giờ giao dịch của tác giả Matt Giannino, cung cấp cho người đọc các quy tắc rõ ràng để cải thiện khả năng thực thi, giảm thiểu thua lỗ và tận dụng tối đa các biến động của thị trường chứng khoán.', 0, 0, 0, true, now(), now(), 'Nearly_Bulletproof_Setups_2.png', 'Nearly_Bulletproof_Setups_2.pdf') ON CONFLICT (isbn) WHERE isbn IS NOT NULL DO NOTHING;


INSERT INTO books (title, author, isbn, publisher, publication_year, language, pages, category_id, price, original_price, stock, description, rating_avg, review_count, sold_count, active, created_at, updated_at, cover_key, file_key) 
VALUES ('Nhà Giả Kim', 'Paulo Coelho', NULL, 'Nhà Xuất Bản Văn Học', NULL, 'vi', 108, (SELECT id FROM categories WHERE name = 'Fiction & Literature'), 630000, 819000, 100, 'Cuốn tiểu thuyết "Nhà Giả Kim" của tác giả Paulo Coelho xoay quanh chủ đề về hành trình theo đuổi ước mơ và khám phá vận mệnh cá nhân của mỗi con người. Nội dung chính kể về Santiago, một cậu bé chăn cừu người Tây Ban Nha luôn mang trong mình khao khát phiêu lưu và một giấc mơ lặp đi lặp lại về việc tìm kiếm một kho báu được chôn giấu gần Kim Tự Tháp Ai Cập. Trên chuyến hành trình dài xuyên qua sa mạc, cậu đã gặp gỡ vị vua già Melchisedek, bán bầy cừu, làm việc tại một cửa hàng pha lê ở châu Phi, băng qua sa mạc Sahara khắc nghiệt, tìm thấy tình yêu với cô gái Fatima tại ốc đảo, và được nhà luyện kim đan chỉ dạy cách lắng nghe tiếng nói của trái tim cũng như thấu hiểu ngôn ngữ của vũ trụ. Đối tượng phù hợp của cuốn sách là mọi độc giả yêu thích văn học, những người đang tìm kiếm cảm hứng sống, hoặc những ai đang băn khoăn trên con đường định hướng cuộc đời. Giá trị sâu sắc của tác phẩm nằm ở thông điệp triết lý: khi một người thực sự quyết tâm muốn điều gì, cả vũ trụ sẽ chung sức giúp họ đạt được, qua đó khuyến khích chúng ta dũng cảm đối mặt với thử thách và theo đuổi vận mệnh.', 0, 0, 0, true, now(), now(), 'Nha_Gia_Kim_Paulo_Coelho.png', 'Nha_Gia_Kim_Paulo_Coelho.pdf') ;


INSERT INTO books (title, author, isbn, publisher, publication_year, language, pages, category_id, price, original_price, stock, description, rating_avg, review_count, sold_count, active, created_at, updated_at, cover_key, file_key) 
VALUES ('Phi Lý Một Cách Hợp Lý', 'Dan Ariely', NULL, 'Nhà Xuất Bản Thế Giới', NULL, 'vi', NULL, (SELECT id FROM categories WHERE name = 'Psychology & Self-Help'), 645000, 838500, 100, 'Cuốn sách "Phi Lý Một Cách Hợp Lý" (Irrationally Yours) của Dan Ariely tập trung vào chủ đề tâm lý học và kinh tế học hành vi, nhằm khám phá những góc khuất trong bản chất con người. Nội dung chính của tác phẩm được xây dựng dưới dạng các câu hỏi và câu trả lời từ chuyên mục "Ask Ariely" trên báo Wall Street Journal, nơi tác giả giải đáp hàng loạt các tình huống đời thường dưới lăng kính khoa học. Sách đề cập đến nhiều vấn đề thực tế như sự khó khăn khi ăn kiêng do xu hướng tập trung vào sự thỏa mãn nhất thời, tâm lý ghét mất mát ảnh hưởng đến các quyết định tài chính, cách giải quyết xung đột trong các mối quan hệ, hay sự phi lý trong việc mua nhẫn đính hôn, hẹn hò trực tuyến và cách xử lý những quyết định khó khăn. Đối tượng phù hợp của sách là đông đảo độc giả đại chúng, những ai yêu thích tâm lý học, muốn tìm hiểu nguyên nhân ẩn sau các hành vi con người và tìm kiếm lời khuyên thiết thực cho cuộc sống. Giá trị của cuốn sách nằm ở sự kết hợp tài tình giữa sự hài hước và kiến thức khoa học xã hội sâu sắc, giúp người đọc nhận ra sự bất hợp lý của bản thân để từ đó đưa ra các lựa chọn khôn ngoan hơn.', 0, 0, 0, true, now(), now(), 'Phi_Ly_Mot_Cach_Hop_Ly.png', 'Phi_Ly_Mot_Cach_Hop_Ly.pdf') ;


INSERT INTO books (title, author, isbn, publisher, publication_year, language, pages, category_id, price, original_price, stock, description, rating_avg, review_count, sold_count, active, created_at, updated_at, cover_key, file_key) 
VALUES ('Practical Machine Learning for Computer Vision', 'Valliappa Lakshmanan, Martin Görner, Ryan Gillard', '9781098102364', 'O''Reilly Media, Inc.', 2021, 'en', NULL, (SELECT id FROM categories WHERE name = 'Technology & Computing'), 660000, 858000, 100, 'Cuốn sách "Practical Machine Learning for Computer Vision" mang đến kiến thức toàn diện về chủ đề thị giác máy tính ứng dụng học máy và học sâu. Nội dung chính của tác phẩm dẫn dắt người đọc qua toàn bộ quy trình xây dựng một hệ thống học máy hoàn chỉnh cho hình ảnh (end-to-end pipeline) sử dụng hai thư viện là TensorFlow và Keras. Sách bao quát từ các bước cơ bản như thu thập và tạo lập bộ dữ liệu (định dạng TFRecords), tiền xử lý và tăng cường dữ liệu, cho đến việc xây dựng và lựa chọn các kiến trúc mạng nơ-ron tích chập (CNN) nổi tiếng như ResNet, MobileNet hay EfficientNet. Ngoài ra, sách còn đi sâu vào các bài toán nâng cao như phát hiện đối tượng (YOLO, RetinaNet), phân vùng hình ảnh (U-Net, Mask R-CNN), tạo hình ảnh (Autoencoder, GAN), đo lường, đếm đối tượng, và ước tính tư thế. Đối tượng phù hợp là các lập trình viên phần mềm, kỹ sư học máy và nhà khoa học dữ liệu muốn áp dụng trí tuệ nhân tạo vào lĩnh vực xử lý ảnh. Giá trị lớn nhất của cuốn sách là những hướng dẫn thực hành sát với thực tế sản xuất, đi kèm mã nguồn mở và các phương pháp giúp triển khai, giải thích và quản lý các mô hình quy mô lớn.', 0, 0, 0, true, now(), now(), 'Designing_Machine_Learning.png', 'Designing_Machine_Learning.pdf') ON CONFLICT (isbn) WHERE isbn IS NOT NULL DO NOTHING;


INSERT INTO books (title, author, isbn, publisher, publication_year, language, pages, category_id, price, original_price, stock, description, rating_avg, review_count, sold_count, active, created_at, updated_at, cover_key, file_key) 
VALUES ('Prompt Engineering for Generative AI', 'James Phoenix, Mike Taylor', '9781098153434', 'O''Reilly Media, Inc.', 2024, 'en', NULL, (SELECT id FROM categories WHERE name = 'Technology & Computing'), 75000, 97500, 100, 'Cuốn sách "Prompt Engineering for Generative AI" là một tài liệu chuyên sâu về chủ đề kỹ thuật thiết kế câu lệnh (prompt engineering) dành cho các mô hình AI tạo sinh, bao gồm cả mô hình ngôn ngữ lớn (LLM) như ChatGPT và mô hình khuếch tán hình ảnh như Midjourney hay Stable Diffusion. Nội dung chính của sách tập trung vào "Năm nguyên tắc thiết kế câu lệnh" cốt lõi: Đưa ra định hướng, Chỉ định định dạng, Cung cấp ví dụ, Đánh giá chất lượng và Phân chia công việc. Sách hướng dẫn chi tiết cách áp dụng các nguyên tắc này để tạo văn bản (như tạo danh sách, xuất dữ liệu JSON/YAML, đóng vai nhân vật) và tạo hình ảnh (áp dụng phong cách nghệ thuật, sửa lỗi hình ảnh). Đặc biệt, tài liệu cũng đi sâu vào các kỹ thuật nâng cao thông qua việc sử dụng thư viện LangChain, tích hợp cơ sở dữ liệu vector để truy xuất thông tin (RAG), và xây dựng các tác nhân AI đàm thoại. Đối tượng phù hợp của cuốn sách là các lập trình viên, kỹ sư AI, chuyên gia tiếp thị và những người muốn tích hợp AI tự động vào hệ thống. Giá trị nổi bật của tác phẩm là mang lại tư duy và nguyên tắc làm việc bền vững, không bị lỗi thời bất chấp sự thay đổi của các mô hình AI, giúp tạo ra kết quả đáng tin cậy ở quy mô doanh nghiệp.', 0, 0, 0, true, now(), now(), 'Prompt_Engineering_for_Gene.png', 'Prompt_Engineering_for_Gene.pdf') ON CONFLICT (isbn) WHERE isbn IS NOT NULL DO NOTHING;


INSERT INTO books (title, author, isbn, publisher, publication_year, language, pages, category_id, price, original_price, stock, description, rating_avg, review_count, sold_count, active, created_at, updated_at, cover_key, file_key) 
VALUES ('Prompt Engineering for LLMs', 'John Berryman, Albert Ziegler', '9781098156152', 'O''Reilly Media, Inc.', 2025, 'en', NULL, (SELECT id FROM categories WHERE name = 'Technology & Computing'), 90000, 117000, 100, 'Cuốn sách "Prompt Engineering for LLMs" đi sâu vào nghệ thuật và khoa học xây dựng các ứng dụng dựa trên Mô hình Ngôn ngữ Lớn (LLM). Nội dung chính của cuốn sách bắt đầu bằng việc giải mã cách thức hoạt động thực sự của LLM — từ kiến trúc Transformer, quá trình mã hóa (tokenization), đến cơ chế tự hồi quy dự đoán từng từ dựa trên xác suất, khẳng định rằng LLM bản chất chỉ là những cỗ máy hoàn thiện văn bản. Từ nền tảng đó, sách hướng dẫn người đọc cách thu thập, phân loại và tổ chức ngữ cảnh để xây dựng một câu lệnh (prompt) tối ưu, kết hợp nội dung tĩnh và động thông qua kỹ thuật RAG. Sách cũng đề cập đến các kỹ năng nâng cao như định dạng đầu ra, kiểm soát mô hình qua logprobs, tinh chỉnh (fine-tuning) và xây dựng các tác nhân đàm thoại có khả năng sử dụng công cụ thực tế. Đối tượng phù hợp nhất là các kỹ sư ứng dụng, nhà phát triển phần mềm và các chuyên gia thiết kế câu lệnh muốn tích hợp LLM vào phần mềm thực tế. Giá trị cốt lõi của cuốn sách là giúp người đọc thoát khỏi góc nhìn "phép thuật" về AI, thay vào đó cung cấp phương pháp tiếp cận có hệ thống và tư duy kỹ thuật rõ ràng để điều khiển mô hình.', 0, 0, 0, true, now(), now(), 'Prompt_Engineering_for_LLMs.png', 'Prompt_Engineering_for_LLMs.pdf') ON CONFLICT (isbn) WHERE isbn IS NOT NULL DO NOTHING;


INSERT INTO books (title, author, isbn, publisher, publication_year, language, pages, category_id, price, original_price, stock, description, rating_avg, review_count, sold_count, active, created_at, updated_at, cover_key, file_key) 
VALUES ('RAG-Driven Generative AI', 'Denis Rothman', '9781807424954', 'Packt Publishing', 2026, 'en', NULL, (SELECT id FROM categories WHERE name = 'Technology & Computing'), 105000, 136500, 100, 'Cuốn sách "RAG-Driven Generative AI" mang đến một cách tiếp cận mang tính cách mạng về chủ đề AI tạo sinh kết hợp sinh văn bản tăng cường truy xuất (RAG) ở cấp độ doanh nghiệp. Nội dung chính của sách tập trung vào kiến trúc hệ thống nơi AI được đưa đến gần dữ liệu thay vì trích xuất dữ liệu ra ngoài, qua đó đảm bảo chủ quyền và bảo mật dữ liệu tuyệt đối. Sách hướng dẫn chi tiết cách xây dựng các hệ thống đa tác vụ (MAS-RAG), DualRAG, GraphRAG và các đường ống xử lý video đa phương thức hoạt động trực tiếp trong hệ sinh thái Oracle Database 23ai có tích hợp tính năng tìm kiếm vector. Người đọc cũng sẽ được học cách tinh chỉnh mô hình (fine-tuning) cho các nhiệm vụ cụ thể, áp dụng phản hồi từ con người (RLHF), đánh giá hiệu suất tác nhân và quản lý vòng đời hệ thống. Đối tượng phù hợp của sách là các kiến trúc sư AI doanh nghiệp, lập trình viên cấp cao và chuyên gia cơ sở dữ liệu ưu tiên các vấn đề về bảo mật. Giá trị đặc biệt của cuốn sách nằm ở việc cung cấp các bản thiết kế kiến trúc thực chiến giúp xóa bỏ hiện tượng "ảo giác" của AI và chuyển đổi các cơ sở dữ liệu truyền thống thành những cỗ máy thông minh và hoàn toàn tự chủ.', 0, 0, 0, true, now(), now(), 'RAG-Driven_Generative_AI_Bu.png', 'RAG-Driven_Generative_AI_Bu.pdf') ON CONFLICT (isbn) WHERE isbn IS NOT NULL DO NOTHING;


INSERT INTO books (title, author, isbn, publisher, publication_year, language, pages, category_id, price, original_price, stock, description, rating_avg, review_count, sold_count, active, created_at, updated_at, cover_key, file_key) 
VALUES ('Reassembling the Social: An Introduction to Actor-Network-Theory', 'Bruno Latour', '9780199256044', 'Oxford University Press', 2005, 'en', NULL, (SELECT id FROM categories WHERE name = 'Social Sciences'), 120000, 156000, 100, 'Cuốn sách "Reassembling the Social" của Bruno Latour là một tác phẩm nền tảng về chủ đề Lý thuyết Mạng lưới Hành tố (Actor-Network-Theory hay ANT). Nội dung chính của cuốn sách là một cuộc tái định nghĩa triệt để về khái niệm "xã hội". Thay vì coi xã hội là một bối cảnh vô hình hay một loại vật chất có sẵn định hình hành vi, tác giả lập luận rằng "xã hội" chỉ là kết quả của các mối liên kết liên tục được lắp ráp giữa những tác nhân không đồng nhất, bao gồm cả con người và các vật thể phi con người (đồ vật). Sách phân tích năm nguồn gốc của sự không chắc chắn (về nhóm, hành động, vai trò của đồ vật, sự thật so với mối quan tâm, và cách viết báo cáo) nhằm hướng dẫn người đọc cách lập bản đồ các mạng lưới này. Đối tượng phù hợp của cuốn sách là các nhà xã hội học, nhân chủng học, học giả nghiên cứu khoa học và công nghệ (STS), cùng những ai muốn tìm kiếm một phương pháp luận thực nghiệm mới. Giá trị cốt lõi của tác phẩm là thách thức các quan điểm xã hội học truyền thống, trao "quyền hành động" cho các đồ vật và cung cấp một cẩm nang hướng dẫn thực tế để theo dõi các mối quan hệ xã hội một cách minh bạch mà không vội vàng áp đặt các giả định vĩ mô.', 0, 0, 0, true, now(), now(), 'Reassembling_the_Social_An.png', 'Reassembling_the_Social_An.pdf') ON CONFLICT (isbn) WHERE isbn IS NOT NULL DO NOTHING;
